/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2009 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Data declarations

extern _UNKNOWN loc_11782; // weak
extern const WCHAR SourceString; // idb
extern char asc_11B4A[2]; // weak
extern wchar_t a_lnk[5]; // weak
extern char asc_11BA2[2]; // weak
extern wchar_t a_tmp[5]; // weak
// extern void *IoDriverObjectType; weak
// extern volatile KSYSTEM_TIME KeTickCount;
extern PCWSTR Object; // idb
extern int dword_11F0C; // weak
extern int dword_11F10; // weak
extern _DWORD dword_11F14[5]; // idb
extern int dword_11F28; // weak
extern int dword_11F2C; // weak
extern int dword_11F30; // weak
extern int dword_11F34; // weak
extern int dword_11F38; // weak
extern int dword_11F3C; // weak
extern int dword_11F40; // weak
extern int dword_11F44; // weak
extern int dword_11F48; // weak
extern int dword_11F4C; // weak
extern int dword_11F50; // weak
extern int dword_11F5C; // weak
extern int dword_11F60; // weak
extern int dword_11F68; // weak
extern int dword_11F6C; // weak
extern int dword_11F70; // weak
extern int dword_11F74; // weak
extern int dword_11F78; // weak
extern int dword_11F7C; // weak
extern int dword_11F80; // weak
extern int dword_11F84; // weak
extern int dword_11F88; // weak
extern PDRIVER_OBJECT DriverObject; // idb
extern PDEVICE_OBJECT DeviceObject; // idb

//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

NTSTATUS __stdcall sub_10486(int a1, PIRP Irp);
int sub_10496(); // weak
signed int __cdecl sub_104CB();
// int __userpurge sub_104CF<eax>(int a1<ebp>, int a2, int a3);
int sub_104EC(); // weak
signed int __cdecl sub_10521();
// int __userpurge sub_10525<eax>(int a1<ebp>, int a2, int a3);
PDRIVER_OBJECT __cdecl sub_10542();
int __stdcall sub_10630(int (__stdcall *a1)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD), PCWSTR Object);
void *__cdecl sub_106BE();
NTSTATUS __stdcall sub_10726(PDRIVER_OBJECT DriverObject, int a2);
// unsigned int __userpurge sub_107DE<eax>(int a1<esi>, int a2);
int __stdcall sub_1083C(int, int, int); // weak
signed int __cdecl sub_10895();
// int __userpurge sub_10899<eax>(int a1<ebp>, int a2, int a3, int a4);
// char __userpurge sub_108B6<al>(int a1<ebx>, int a2);
NTSTATUS __stdcall sub_10906(int a1, PIRP Irp);
// void __usercall sub_10980(int a1<edi>);
void __stdcall sub_109EC(int TargetDevice, char a2);
NTSTATUS __stdcall sub_10A3C(int a1, PDEVICE_OBJECT *DeviceObject);
int __stdcall sub_10A66(int a1, int a2);
int __stdcall sub_10A92(int a1, int a2);
char __stdcall sub_10AB4(int a1);
bool __stdcall sub_10AEA(int a1);
unsigned int __stdcall sub_10B12(PDEVICE_OBJECT SourceDevice, PDEVICE_OBJECT TargetDevice, int a3);
NTSTATUS __stdcall sub_10B44(int a1, PIRP Irp);
// void __usercall sub_10B6A(int a1<eax>, PMDL *a2<esi>);
// char __userpurge sub_10B98<al>(int a1<eax>, int a2<edi>, int a3);
void __cdecl WorkerRoutine(int a1, PVOID P);
int __stdcall sub_10C2A(int, int, int); // weak
signed int __cdecl sub_10D17();
// int __userpurge sub_10D1B<eax>(int a1<ebp>, int a2, int a3, int a4);
int __stdcall sub_10D38(PDEVICE_OBJECT DeviceObject, int, int, int); // idb
NTSTATUS __stdcall sub_10DC8(int a1, PIRP Irp);
// char __userpurge sub_10E6A<al>(int a1<eax>, int a2<ecx>, int a3);
char __thiscall sub_10E98(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
char __thiscall sub_10EEC(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
char __thiscall sub_10F40(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
char __thiscall sub_10F94(void *this, int a2, int a3, int a4, int a5, int a6);
char __thiscall sub_10FDE(void *this, int a2, int a3, int a4, int a5, int a6);
char __thiscall sub_11028(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10);
char __thiscall sub_1107E(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
char __thiscall sub_110CE(void *this, int a2, int a3, int a4, int a5);
char __thiscall sub_11116(void *this, int a2, int a3, int a4, int a5, int a6);
char __thiscall sub_11160(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10);
void __stdcall sub_111B6(PDEVICE_OBJECT DeviceObject, PDEVICE_OBJECT TargetDevice);
char __thiscall sub_111D6(void *this, int a2, int a3, int a4, int a5, int a6);
char __thiscall sub_11220(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
char __thiscall sub_11270(void *this, int a2, int a3, int a4);
char __thiscall sub_112B4(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
char __thiscall sub_11304(void *this, int a2, int a3, int a4, int a5);
char __thiscall sub_1134C(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11);
char __thiscall sub_113A6(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11);
char __thiscall sub_11400(void *this, int a2, int a3, int a4);
char __thiscall sub_11444(void *this, int a2, int a3, int a4, int a5);
char __thiscall sub_1148C(void *this, int a2, int a3, int a4);
// char __userpurge sub_114DA<al>(unsigned __int16 *a1<eax>, int *a2, int a3);
char __stdcall sub_11538(int a1, int a2, int a3, int a4);
// char __userpurge sub_115F6<al>(int a1<esi>, int a2, unsigned int a3, int a4);
char __stdcall sub_11688(void *a1, int a2, int a3, int a4, int a5);
// int _SEH_epilog4(void); weak
int __cdecl sub_11830(int a1, int a2, int a3);
// int __usercall sub_1198C<eax>(int a1<ebp>, int a2, int a3, unsigned int a4);
int __cdecl loc_11A1C(int, int, int); // weak
int __thiscall sub_11A7E(void *this);
int __thiscall sub_11AAE(void *this);
int loc_11AC3(); // weak
int __fastcall sub_11AC8(int a1, unsigned int a2, int a3, int a4);
// int __userpurge sub_11AED<eax>(int result<eax>, int a2<ebp>, int a3);
// int __usercall sub_11B0C<eax>(int (*a1)(void)<eax>);
// int __stdcall RtlUnwind(_DWORD, _DWORD, _DWORD, _DWORD); weak
// NTSTATUS __stdcall IoCreateDevice(PDRIVER_OBJECT DriverObject, ULONG DeviceExtensionSize, PUNICODE_STRING DeviceName, ULONG DeviceType, ULONG DeviceCharacteristics, BOOLEAN Exclusive, PDEVICE_OBJECT *DeviceObject);
// void __stdcall IoDeleteDevice(PDEVICE_OBJECT DeviceObject);
// int __stdcall IoRegisterFsRegistrationChange(_DWORD, _DWORD); weak
// LONG_PTR __fastcall ObfDereferenceObject(PVOID Object);
// void __stdcall RtlInitUnicodeString(PUNICODE_STRING DestinationString, PCWSTR SourceString);
// PVOID __stdcall MmGetSystemRoutineAddress(PUNICODE_STRING SystemRoutineName);
// void __fastcall IofCompleteRequest(PIRP Irp, CCHAR PriorityBoost);
// NTSTATUS __stdcall KeDelayExecutionThread(KPROCESSOR_MODE WaitMode, BOOLEAN Alertable, PLARGE_INTEGER Interval);
// void __stdcall ExFreePoolWithTag(PVOID P, ULONG Tag);
// PVOID __stdcall ExAllocatePool(POOL_TYPE PoolType, SIZE_T NumberOfBytes);
// NTSTATUS __fastcall IofCallDriver(PDEVICE_OBJECT DeviceObject, PIRP Irp);
// void __stdcall IoDetachDevice(PDEVICE_OBJECT TargetDevice);
// PDEVICE_OBJECT __stdcall IoAttachDeviceToDeviceStack(PDEVICE_OBJECT SourceDevice, PDEVICE_OBJECT TargetDevice);
// void __stdcall IoFreeMdl(PMDL Mdl);
// void __stdcall MmUnlockPages(PMDL MemoryDescriptorList);
// void __stdcall MmProbeAndLockPages(PMDL MemoryDescriptorList, KPROCESSOR_MODE AccessMode, LOCK_OPERATION Operation);
// PMDL __stdcall IoAllocateMdl(PVOID VirtualAddress, ULONG Length, BOOLEAN SecondaryBuffer, BOOLEAN ChargeQuota, PIRP Irp);
// void __stdcall IoFreeWorkItem(PIO_WORKITEM IoWorkItem);
// void __stdcall IoQueueWorkItem(PIO_WORKITEM IoWorkItem, PIO_WORKITEM_ROUTINE WorkerRoutine, WORK_QUEUE_TYPE QueueType, PVOID Context);
// PIO_WORKITEM __stdcall IoAllocateWorkItem(PDEVICE_OBJECT DeviceObject);
// int __cdecl toupper(int);
// void *__cdecl memmove(void *, const void *, size_t);
NTSTATUS __stdcall DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath);


//----- (00010486) --------------------------------------------------------
NTSTATUS __stdcall sub_10486(int a1, PIRP Irp)
{
  return sub_10B44(a1, Irp);
}

//----- (000104CB) --------------------------------------------------------
signed int __cdecl sub_104CB()
{
  return 1;
}

//----- (000104CF) --------------------------------------------------------
int __userpurge sub_104CF<eax>(int a1<ebp>, int a2, int a3)
{
  *(_DWORD *)(a1 - 4) = -2;
  return _SEH_epilog4();
}
// 11809: using guessed type int _SEH_epilog4(void);

//----- (00010521) --------------------------------------------------------
signed int __cdecl sub_10521()
{
  return 1;
}

//----- (00010525) --------------------------------------------------------
int __userpurge sub_10525<eax>(int a1<ebp>, int a2, int a3)
{
  *(_DWORD *)(a1 - 4) = -2;
  return _SEH_epilog4();
}
// 11809: using guessed type int _SEH_epilog4(void);

//----- (00010542) --------------------------------------------------------
PDRIVER_OBJECT __cdecl sub_10542()
{
  PDRIVER_OBJECT result; // eax@1

  result = DriverObject;
  dword_11F28 = 112;
  dword_11F2C = (int)sub_10E98;
  dword_11F30 = (int)sub_10EEC;
  dword_11F34 = (int)sub_10F40;
  dword_11F38 = (int)sub_10F94;
  dword_11F3C = (int)sub_10FDE;
  dword_11F40 = (int)sub_11028;
  dword_11F44 = (int)sub_1107E;
  dword_11F48 = (int)sub_110CE;
  dword_11F4C = (int)sub_11116;
  dword_11F50 = (int)sub_11160;
  dword_11F5C = (int)sub_111B6;
  dword_11F60 = (int)sub_111D6;
  dword_11F68 = (int)sub_11220;
  dword_11F6C = (int)sub_11270;
  dword_11F70 = (int)sub_112B4;
  dword_11F74 = (int)sub_11304;
  dword_11F78 = (int)sub_1134C;
  dword_11F7C = (int)sub_113A6;
  dword_11F80 = (int)sub_11400;
  dword_11F84 = (int)sub_11444;
  dword_11F88 = (int)sub_1148C;
  DriverObject->FastIoDispatch = (PFAST_IO_DISPATCH)&dword_11F28;
  return result;
}
// 11F28: using guessed type int dword_11F28;
// 11F2C: using guessed type int dword_11F2C;
// 11F30: using guessed type int dword_11F30;
// 11F34: using guessed type int dword_11F34;
// 11F38: using guessed type int dword_11F38;
// 11F3C: using guessed type int dword_11F3C;
// 11F40: using guessed type int dword_11F40;
// 11F44: using guessed type int dword_11F44;
// 11F48: using guessed type int dword_11F48;
// 11F4C: using guessed type int dword_11F4C;
// 11F50: using guessed type int dword_11F50;
// 11F5C: using guessed type int dword_11F5C;
// 11F60: using guessed type int dword_11F60;
// 11F68: using guessed type int dword_11F68;
// 11F6C: using guessed type int dword_11F6C;
// 11F70: using guessed type int dword_11F70;
// 11F74: using guessed type int dword_11F74;
// 11F78: using guessed type int dword_11F78;
// 11F7C: using guessed type int dword_11F7C;
// 11F80: using guessed type int dword_11F80;
// 11F84: using guessed type int dword_11F84;
// 11F88: using guessed type int dword_11F88;

//----- (00010630) --------------------------------------------------------
int __stdcall sub_10630(int (__stdcall *a1)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD), PCWSTR Object)
{
  int result; // eax@1
  int i; // esi@3
  LSA_UNICODE_STRING DestinationString; // [sp+10h] [bp-20h]@1
  CPPEH_RECORD ms_exc; // [sp+18h] [bp-18h]@1

  ms_exc.disabled = 0;
  RtlInitUnicodeString(&DestinationString, Object);
  result = a1(&DestinationString, 64, 0, 0, IoDriverObjectType, 0, 0, &Object);
  if ( result >= 0 )
  {
    for ( i = *((_DWORD *)Object + 1); i; i = *(_DWORD *)(i + 12) )
      sub_109EC(i, 1);
    ObfDereferenceObject((PVOID)Object);
    result = 0;
  }
  else
  {
    ms_exc.disabled = -2;
  }
  return result;
}
// 11C10: using guessed type void *IoDriverObjectType;

//----- (000106BE) --------------------------------------------------------
void *__cdecl sub_106BE()
{
  void *result; // eax@1
  void *v1; // esi@1
  LSA_UNICODE_STRING DestinationString; // [sp+10h] [bp-24h]@1
  int i; // [sp+18h] [bp-1Ch]@2
  CPPEH_RECORD ms_exc; // [sp+1Ch] [bp-18h]@1

  ms_exc.disabled = 0;
  RtlInitUnicodeString(&DestinationString, &SourceString);
  result = MmGetSystemRoutineAddress(&DestinationString);
  v1 = result;
  if ( result )
  {
    for ( i = 0; i < 3; ++i )
      result = (void *)sub_10630(
                         (int (__stdcall *)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD))v1,
                         (&Object)[2 * i]);
  }
  return result;
}

//----- (00010726) --------------------------------------------------------
NTSTATUS __stdcall sub_10726(PDRIVER_OBJECT DriverObject, int a2)
{
  NTSTATUS v2; // esi@1
  signed int v3; // eax@2
  NTSTATUS result; // eax@7

  ::DriverObject = DriverObject;
  v2 = IoCreateDevice(DriverObject, 8u, 0, 8u, 0x100u, 0, &DeviceObject);
  if ( v2 < 0 )
    goto LABEL_11;
  sub_10A92((int)DeviceObject->DeviceExtension, 0);
  v3 = 56;
  do
  {
    *(_DWORD *)((char *)&::DriverObject->Type + v3) = sub_10486;
    v3 += 4;
  }
  while ( v3 <= 164 );
  ::DriverObject->MajorFunction[13] = (PDRIVER_DISPATCH)sub_10496;
  ::DriverObject->MajorFunction[12] = (PDRIVER_DISPATCH)sub_104EC;
  sub_10542();
  sub_106BE();
  v2 = IoRegisterFsRegistrationChange(::DriverObject, sub_109EC);
  if ( v2 >= 0 )
  {
    result = 0;
  }
  else
  {
LABEL_11:
    if ( DeviceObject )
      IoDeleteDevice(DeviceObject);
    ::DriverObject->FastIoDispatch = 0;
    result = v2;
  }
  return result;
}
// 10496: using guessed type int sub_10496();
// 104EC: using guessed type int sub_104EC();
// 11C08: using guessed type int __stdcall IoRegisterFsRegistrationChange(_DWORD, _DWORD);

//----- (000107DE) --------------------------------------------------------
unsigned int __userpurge sub_107DE<eax>(int a1<esi>, int a2)
{
  int v2; // edi@1
  unsigned int v3; // ebx@2
  LARGE_INTEGER Interval; // [sp+8h] [bp-Ch]@3
  unsigned int v6; // [sp+10h] [bp-4h]@1

  v2 = *(_DWORD *)(a1 + 40);
  sub_10A66(a1, a2);
  v6 = 0;
  while ( 1 )
  {
    v3 = sub_10B12((PDEVICE_OBJECT)a1, (PDEVICE_OBJECT)a2, v2);
    if ( (signed int)v3 >= 0 )
      break;
    Interval = (LARGE_INTEGER)-5000000i64;
    KeDelayExecutionThread(0, 0, &Interval);
    ++v6;
    if ( v6 >= 8 )
      return v3;
  }
  return 0;
}

//----- (00010895) --------------------------------------------------------
signed int __cdecl sub_10895()
{
  return 1;
}

//----- (00010899) --------------------------------------------------------
int __userpurge sub_10899<eax>(int a1<ebp>, int a2, int a3, int a4)
{
  *(_DWORD *)(a1 - 4) = -2;
  return _SEH_epilog4();
}
// 11809: using guessed type int _SEH_epilog4(void);

//----- (000108B6) --------------------------------------------------------
char __userpurge sub_108B6<al>(int a1<ebx>, int a2)
{
  PVOID v2; // eax@1
  char result; // al@2
  const void *v4; // esi@3
  int v5; // ecx@3

  v2 = ExAllocatePool(0, 4u);
  if ( v2 )
  {
    *(_DWORD *)v2 = a2;
    v4 = *(const void **)(a1 + 96);
    memcpy((char *)v4 - 36, v4, 0x1Cu);
    *((_BYTE *)v4 - 33) = 0;
    v5 = *(_DWORD *)(a1 + 96) - 36;
    *(_DWORD *)(v5 + 32) = v2;
    *(_DWORD *)(v5 + 28) = sub_1083C;
    *(_BYTE *)(v5 + 3) = -32;
    result = 1;
  }
  else
  {
    result = 0;
  }
  return result;
}
// 1083C: using guessed type int __stdcall sub_1083C(int, int, int);

//----- (00010906) --------------------------------------------------------
NTSTATUS __stdcall sub_10906(int a1, PIRP Irp)
{
  NTSTATUS v2; // eax@1
  NTSTATUS v3; // esi@1
  NTSTATUS result; // eax@2
  PDEVICE_OBJECT DeviceObject; // [sp+8h] [bp-4h]@1

  DeviceObject = 0;
  v2 = sub_10A3C(a1, &DeviceObject);
  v3 = v2;
  if ( v2 >= 0 )
  {
    sub_10A92(
      (int)DeviceObject->DeviceExtension,
      *(_DWORD *)(*((_DWORD *)Irp->Tail.Overlay.CurrentStackLocation + 1) + 12));
    if ( !sub_108B6((int)Irp, (int)DeviceObject) )
    {
      ++Irp->CurrentLocation;
      Irp->Tail.Overlay.CurrentStackLocation = (struct _IRP::$::$::$::$A02EC6A2CE86544F716F4825015773AC::_IO_STACK_LOCATION *)((char *)Irp->Tail.Overlay.CurrentStackLocation + 36);
    }
    result = IofCallDriver(**(PDEVICE_OBJECT **)(a1 + 40), Irp);
  }
  else
  {
    Irp->IoStatus.Information = 0;
    Irp->IoStatus.Status = v2;
    IofCompleteRequest(Irp, 0);
    result = v3;
  }
  return result;
}

//----- (00010980) --------------------------------------------------------
void __usercall sub_10980(int a1<edi>)
{
  int v1; // eax@1
  int v2; // esi@6
  PDEVICE_OBJECT SourceDevice; // [sp+0h] [bp-4h]@1

  v1 = *(_DWORD *)(a1 + 44);
  SourceDevice = 0;
  if ( v1 == 8 || v1 == 3 || v1 == 20 )
  {
    if ( !sub_10AB4(a1) )
    {
      if ( sub_10A3C(a1, &SourceDevice) >= 0 )
      {
        sub_10A66((int)SourceDevice, a1);
        v2 = (int)SourceDevice->DeviceExtension;
        sub_10A92((int)SourceDevice->DeviceExtension, 0);
        if ( (signed int)sub_10B12(SourceDevice, (PDEVICE_OBJECT)a1, v2) < 0 )
          IoDeleteDevice(SourceDevice);
      }
    }
  }
}

//----- (000109EC) --------------------------------------------------------
void __stdcall sub_109EC(int TargetDevice, char a2)
{
  struct _DEVICE_OBJECT *v2; // edi@3
  int v3; // esi@3

  if ( a2 )
  {
    sub_10980(TargetDevice);
  }
  else
  {
    v3 = *(_DWORD *)(TargetDevice + 16);
    v2 = (struct _DEVICE_OBJECT *)TargetDevice;
    while ( v3 )
    {
      if ( sub_10AEA(v3) )
      {
        IoDetachDevice(v2);
        IoDeleteDevice((PDEVICE_OBJECT)v3);
        return;
      }
      v2 = (struct _DEVICE_OBJECT *)v3;
      v3 = *(_DWORD *)(v3 + 16);
    }
  }
}

//----- (00010A3C) --------------------------------------------------------
NTSTATUS __stdcall sub_10A3C(int a1, PDEVICE_OBJECT *DeviceObject)
{
  return IoCreateDevice(DriverObject, 8u, 0, *(_DWORD *)(a1 + 44), 0, 0, DeviceObject);
}

//----- (00010A66) --------------------------------------------------------
int __stdcall sub_10A66(int a1, int a2)
{
  int result; // eax@1
  int v3; // edx@1

  v3 = *(_DWORD *)(a2 + 28);
  result = a1;
  *(_DWORD *)(result + 28) |= v3 & 0x40014;
  *(_DWORD *)(result + 32) |= *(_DWORD *)(a2 + 32) & 0x100;
  return result;
}

//----- (00010A92) --------------------------------------------------------
int __stdcall sub_10A92(int a1, int a2)
{
  int result; // eax@1

  *(_DWORD *)a1 = 0;
  *(_DWORD *)(a1 + 4) = 0;
  result = a2;
  *(_DWORD *)a1 = 0;
  *(_DWORD *)(a1 + 4) = a2;
  return result;
}

//----- (00010AB4) --------------------------------------------------------
char __stdcall sub_10AB4(int a1)
{
  int v1; // eax@1

  v1 = a1;
  if ( a1 )
  {
    while ( 1 )
    {
      v1 = *(_DWORD *)(v1 + 16);
      if ( !v1 )
        break;
      if ( *(PDRIVER_OBJECT *)(v1 + 8) == DriverObject && *(_DWORD *)(v1 + 40) )
        return 1;
    }
  }
  return 0;
}

//----- (00010AEA) --------------------------------------------------------
bool __stdcall sub_10AEA(int a1)
{
  return a1 && *(PDRIVER_OBJECT *)(a1 + 8) == DriverObject;
}

//----- (00010B12) --------------------------------------------------------
unsigned int __stdcall sub_10B12(PDEVICE_OBJECT SourceDevice, PDEVICE_OBJECT TargetDevice, int a3)
{
  PDEVICE_OBJECT v4; // eax@1

  *(_DWORD *)a3 = TargetDevice;
  v4 = IoAttachDeviceToDeviceStack(SourceDevice, TargetDevice);
  *(_DWORD *)a3 = v4;
  return (v4 != 0 ? 0x3FFFFFF2 : 0) - 1073741810;
}

//----- (00010B44) --------------------------------------------------------
NTSTATUS __stdcall sub_10B44(int a1, PIRP Irp)
{
  PIRP v3; // edx@1
  PDEVICE_OBJECT *v4; // eax@1

  v3 = Irp;
  v4 = *(PDEVICE_OBJECT **)(a1 + 40);
  ++v3->CurrentLocation;
  v3->Tail.Overlay.CurrentStackLocation = (struct _IRP::$::$::$::$A02EC6A2CE86544F716F4825015773AC::_IO_STACK_LOCATION *)((char *)v3->Tail.Overlay.CurrentStackLocation + 36);
  return IofCallDriver(*v4, Irp);
}

//----- (00010B6A) --------------------------------------------------------
void __usercall sub_10B6A(int a1<eax>, PMDL *a2<esi>)
{
  if ( a2 )
  {
    if ( *a2 == *(PMDL *)(a1 + 4) )
    {
      *(_DWORD *)(a1 + 4) = 0;
      MmUnlockPages(*a2);
      IoFreeMdl(*a2);
    }
    ExFreePoolWithTag(a2, 0);
  }
}

//----- (00010B98) --------------------------------------------------------
char __userpurge sub_10B98<al>(int a1<eax>, int a2<edi>, int a3)
{
  struct _MDL *v3; // eax@1
  struct _MDL *v4; // esi@1
  char result; // al@2

  v3 = IoAllocateMdl(*(PVOID *)(a2 + 60), *(_DWORD *)(a1 + 4), 0, 0, (PIRP)a2);
  v4 = v3;
  if ( v3 )
  {
    MmProbeAndLockPages(v3, 0, IoModifyAccess);
    *(_DWORD *)(a2 + 4) = v4;
    *(_DWORD *)a3 = v4;
    result = 1;
  }
  else
  {
    result = 0;
  }
  return result;
}

//----- (00010BD8) --------------------------------------------------------
void __cdecl WorkerRoutine(int a1, PVOID P)
{
  IofCallDriver(**(PDEVICE_OBJECT **)(a1 + 40), *((PIRP *)P + 1));
  IoFreeWorkItem(*(PIO_WORKITEM *)P);
  ExFreePoolWithTag(P, 0);
}

//----- (00010D17) --------------------------------------------------------
signed int __cdecl sub_10D17()
{
  return 1;
}

//----- (00010D1B) --------------------------------------------------------
int __userpurge sub_10D1B<eax>(int a1<ebp>, int a2, int a3, int a4)
{
  *(_DWORD *)(a1 - 4) = -2;
  return _SEH_epilog4();
}
// 11809: using guessed type int _SEH_epilog4(void);

//----- (00010D38) --------------------------------------------------------
signed int __stdcall sub_10D38(PDEVICE_OBJECT DeviceObject, int a2, int a3, int a4)
{
  PVOID v4; // ebx@1
  signed int result; // eax@2
  PIO_WORKITEM v6; // eax@3
  const void *v7; // esi@4
  int v8; // eax@4

  v4 = ExAllocatePool(0, 8u);
  if ( v4 && (v6 = IoAllocateWorkItem(DeviceObject), *(_DWORD *)v4 = v6, v6) )
  {
    *((_DWORD *)v4 + 1) = a3;
    *(_BYTE *)(a2 + 2) &= 0xFEu;
    *(_DWORD *)(a2 + 16) = 0;
    *(_BYTE *)(*(_DWORD *)(a3 + 96) + 3) |= 1u;
    v7 = *(const void **)(a3 + 96);
    memcpy((char *)v7 - 36, v7, 0x1Cu);
    *((_BYTE *)v7 - 33) = 0;
    v8 = *(_DWORD *)(a3 + 96) - 36;
    *(_DWORD *)(v8 + 28) = sub_10C2A;
    *(_DWORD *)(v8 + 32) = a4;
    *(_BYTE *)(v8 + 3) = -32;
    IoQueueWorkItem(*(PIO_WORKITEM *)v4, (PIO_WORKITEM_ROUTINE)WorkerRoutine, DelayedWorkQueue, v4);
    result = -1073741802;
  }
  else
  {
    result = -1073741670;
  }
  return result;
}
// 10C2A: using guessed type int __stdcall sub_10C2A(int, int, int);

//----- (00010DC8) --------------------------------------------------------
NTSTATUS __stdcall sub_10DC8(int a1, PIRP Irp)
{
  struct _IRP::$::$::$::$A02EC6A2CE86544F716F4825015773AC::_IO_STACK_LOCATION *v2; // eax@1
  int v3; // ecx@1
  int v4; // esi@3
  char v5; // zf@5
  signed int v6; // ecx@5
  int v7; // edi@5
  int v8; // esi@5
  struct _IRP::$::$::$::$A02EC6A2CE86544F716F4825015773AC::_IO_STACK_LOCATION *v10; // esi@14
  struct _IRP::$::$::$::$A02EC6A2CE86544F716F4825015773AC::_IO_STACK_LOCATION *v11; // eax@14

  v2 = Irp->Tail.Overlay.CurrentStackLocation;
  v3 = *((_DWORD *)v2 + 6);
  if ( !(*(_DWORD *)(v3 + 44) & 0x400000) || !v3 )
  {
    v4 = *((_DWORD *)v2 + 2);
    if ( !v4 )
      goto LABEL_17;
    if ( *(_WORD *)v4 != 76 )
      goto LABEL_17;
    v8 = *(_DWORD *)(v4 + 4);
    v6 = 19;
    v5 = 1;
    v7 = (int)"{";
    do
    {
      if ( !v6 )
        break;
      v5 = *(_DWORD *)v8 == *(_DWORD *)v7;
      v8 += 4;
      v7 += 4;
      --v6;
    }
    while ( v5 );
    if ( !v5 )
    {
LABEL_17:
      *((_BYTE *)v2 + 3) |= 1u;
      v10 = Irp->Tail.Overlay.CurrentStackLocation;
      memcpy((char *)v10 - 36, (const void *)v10, 0x1Cu);
      *((_BYTE *)v10 - 33) = 0;
      v11 = Irp->Tail.Overlay.CurrentStackLocation;
      *((_DWORD *)v11 - 1) = 0;
      v11 = (struct _IRP::$::$::$::$A02EC6A2CE86544F716F4825015773AC::_IO_STACK_LOCATION *)((char *)v11 - 36);
      *((_DWORD *)v11 + 7) = sub_10C2A;
      *((_BYTE *)v11 + 3) = -32;
      IofCallDriver(**(PDEVICE_OBJECT **)(a1 + 40), Irp);
      return 259;
    }
    v3 = *((_DWORD *)v2 + 6);
  }
  *((_DWORD *)v2 + 2) = 0;
  if ( v3 )
    *(_DWORD *)(v3 + 44) |= 0x400000u;
  return sub_10B44(a1, Irp);
}
// 10C2A: using guessed type int __stdcall sub_10C2A(int, int, int);

//----- (00010E6A) --------------------------------------------------------
char __userpurge sub_10E6A<al>(int a1<eax>, int a2<ecx>, int a3)
{
  char result; // al@2
  int v4; // eax@3
  int v5; // eax@4

  if ( a1 && (v4 = *(_DWORD *)(a1 + 40)) != 0 )
  {
    v5 = *(_DWORD *)v4;
    *(_DWORD *)a2 = v5;
    *(_DWORD *)a3 = *(_DWORD *)(*(_DWORD *)(v5 + 8) + 40);
    result = 1;
  }
  else
  {
    result = 0;
  }
  return result;
}

//----- (00010E98) --------------------------------------------------------
char __thiscall sub_10E98(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9)
{
  char result; // al@5
  void *v10; // [sp+0h] [bp-4h]@1

  v10 = this;
  if ( sub_10E6A(a9, (int)&v10, (int)&a9) && a9 && *(_DWORD *)a9 >= 8u && *(_DWORD *)(a9 + 4) )
    result = (*(int (__stdcall **)(int, int, int, int, int, int, int, void *))(a9 + 4))(a2, a3, a4, a5, a6, a7, a8, v10);
  else
    result = 0;
  return result;
}

//----- (00010EEC) --------------------------------------------------------
char __thiscall sub_10EEC(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9)
{
  char result; // al@5
  void *v10; // [sp+0h] [bp-4h]@1

  v10 = this;
  if ( sub_10E6A(a9, (int)&v10, (int)&a9) && a9 && *(_DWORD *)a9 >= 0xCu && *(_DWORD *)(a9 + 8) )
    result = (*(int (__stdcall **)(int, int, int, int, int, int, int, void *))(a9 + 8))(a2, a3, a4, a5, a6, a7, a8, v10);
  else
    result = 0;
  return result;
}

//----- (00010F40) --------------------------------------------------------
char __thiscall sub_10F40(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9)
{
  char result; // al@5
  void *v10; // [sp+0h] [bp-4h]@1

  v10 = this;
  if ( sub_10E6A(a9, (int)&v10, (int)&a9) && a9 && *(_DWORD *)a9 >= 0x10u && *(_DWORD *)(a9 + 12) )
    result = (*(int (__stdcall **)(int, int, int, int, int, int, int, void *))(a9 + 12))(
               a2,
               a3,
               a4,
               a5,
               a6,
               a7,
               a8,
               v10);
  else
    result = 0;
  return result;
}

//----- (00010F94) --------------------------------------------------------
char __thiscall sub_10F94(void *this, int a2, int a3, int a4, int a5, int a6)
{
  char result; // al@5
  void *v7; // [sp+0h] [bp-4h]@1

  v7 = this;
  if ( sub_10E6A(a6, (int)&v7, (int)&a6) && a6 && *(_DWORD *)a6 >= 0x14u && *(_DWORD *)(a6 + 16) )
    result = (*(int (__stdcall **)(int, int, int, int, void *))(a6 + 16))(a2, a3, a4, a5, v7);
  else
    result = 0;
  return result;
}

//----- (00010FDE) --------------------------------------------------------
char __thiscall sub_10FDE(void *this, int a2, int a3, int a4, int a5, int a6)
{
  char result; // al@5
  void *v7; // [sp+0h] [bp-4h]@1

  v7 = this;
  if ( sub_10E6A(a6, (int)&v7, (int)&a6) && a6 && *(_DWORD *)a6 >= 0x18u && *(_DWORD *)(a6 + 20) )
    result = (*(int (__stdcall **)(int, int, int, int, void *))(a6 + 20))(a2, a3, a4, a5, v7);
  else
    result = 0;
  return result;
}

//----- (00011028) --------------------------------------------------------
char __thiscall sub_11028(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10)
{
  char result; // al@5
  void *v11; // [sp+0h] [bp-4h]@1

  v11 = this;
  if ( sub_10E6A(a10, (int)&v11, (int)&a10) && a10 && *(_DWORD *)a10 >= 0x1Cu && *(_DWORD *)(a10 + 24) )
    result = (*(int (__stdcall **)(int, int, int, int, int, int, int, int, void *))(a10 + 24))(
               a2,
               a3,
               a4,
               a5,
               a6,
               a7,
               a8,
               a9,
               v11);
  else
    result = 0;
  return result;
}

//----- (0001107E) --------------------------------------------------------
char __thiscall sub_1107E(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  char result; // al@5
  void *v9; // [sp+0h] [bp-4h]@1

  v9 = this;
  if ( sub_10E6A(a8, (int)&v9, (int)&a8) && a8 && *(_DWORD *)a8 >= 0x20u && *(_DWORD *)(a8 + 28) )
    result = (*(int (__stdcall **)(int, int, int, int, int, int, void *))(a8 + 28))(a2, a3, a4, a5, a6, a7, v9);
  else
    result = 0;
  return result;
}

//----- (000110CE) --------------------------------------------------------
char __thiscall sub_110CE(void *this, int a2, int a3, int a4, int a5)
{
  char result; // al@5
  void *v6; // [sp+0h] [bp-4h]@1

  v6 = this;
  if ( sub_10E6A(a5, (int)&v6, (int)&a5) && a5 && *(_DWORD *)a5 >= 0x24u && *(_DWORD *)(a5 + 32) )
    result = (*(int (__stdcall **)(int, int, int, void *))(a5 + 32))(a2, a3, a4, v6);
  else
    result = 0;
  return result;
}

//----- (00011116) --------------------------------------------------------
char __thiscall sub_11116(void *this, int a2, int a3, int a4, int a5, int a6)
{
  char result; // al@5
  void *v7; // [sp+0h] [bp-4h]@1

  v7 = this;
  if ( sub_10E6A(a6, (int)&v7, (int)&a6) && a6 && *(_DWORD *)a6 >= 0x28u && *(_DWORD *)(a6 + 36) )
    result = (*(int (__stdcall **)(int, int, int, int, void *))(a6 + 36))(a2, a3, a4, a5, v7);
  else
    result = 0;
  return result;
}

//----- (00011160) --------------------------------------------------------
char __thiscall sub_11160(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10)
{
  char result; // al@5
  void *v11; // [sp+0h] [bp-4h]@1

  v11 = this;
  if ( sub_10E6A(a10, (int)&v11, (int)&a10) && a10 && *(_DWORD *)a10 >= 0x2Cu && *(_DWORD *)(a10 + 40) )
    result = (*(int (__stdcall **)(int, int, int, int, int, int, int, int, void *))(a10 + 40))(
               a2,
               a3,
               a4,
               a5,
               a6,
               a7,
               a8,
               a9,
               v11);
  else
    result = 0;
  return result;
}

//----- (000111B6) --------------------------------------------------------
void __stdcall sub_111B6(PDEVICE_OBJECT DeviceObject, PDEVICE_OBJECT TargetDevice)
{
  IoDetachDevice(TargetDevice);
  IoDeleteDevice(DeviceObject);
}

//----- (000111D6) --------------------------------------------------------
char __thiscall sub_111D6(void *this, int a2, int a3, int a4, int a5, int a6)
{
  char result; // al@5
  void *v7; // [sp+0h] [bp-4h]@1

  v7 = this;
  if ( sub_10E6A(a6, (int)&v7, (int)&a6) && a6 && *(_DWORD *)a6 >= 0x3Cu && *(_DWORD *)(a6 + 56) )
    result = (*(int (__stdcall **)(int, int, int, int, void *))(a6 + 56))(a2, a3, a4, a5, v7);
  else
    result = 0;
  return result;
}

//----- (00011220) --------------------------------------------------------
char __thiscall sub_11220(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  char result; // al@5
  void *v9; // [sp+0h] [bp-4h]@1

  v9 = this;
  if ( sub_10E6A(a8, (int)&v9, (int)&a8) && a8 && *(_DWORD *)a8 >= 0x44u && *(_DWORD *)(a8 + 64) )
    result = (*(int (__stdcall **)(int, int, int, int, int, int, void *))(a8 + 64))(a2, a3, a4, a5, a6, a7, v9);
  else
    result = 0;
  return result;
}

//----- (00011270) --------------------------------------------------------
char __thiscall sub_11270(void *this, int a2, int a3, int a4)
{
  char result; // al@5
  void *v5; // [sp+0h] [bp-4h]@1

  v5 = this;
  if ( sub_10E6A(a4, (int)&v5, (int)&a4) && a4 && *(_DWORD *)a4 >= 0x48u && *(_DWORD *)(a4 + 68) )
    result = (*(int (__stdcall **)(int, int, void *))(a4 + 68))(a2, a3, v5);
  else
    result = 0;
  return result;
}

//----- (000112B4) --------------------------------------------------------
char __thiscall sub_112B4(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  char result; // al@5
  void *v9; // [sp+0h] [bp-4h]@1

  v9 = this;
  if ( sub_10E6A(a8, (int)&v9, (int)&a8) && a8 && *(_DWORD *)a8 >= 0x4Cu && *(_DWORD *)(a8 + 72) )
    result = (*(int (__stdcall **)(int, int, int, int, int, int, void *))(a8 + 72))(a2, a3, a4, a5, a6, a7, v9);
  else
    result = 0;
  return result;
}

//----- (00011304) --------------------------------------------------------
char __thiscall sub_11304(void *this, int a2, int a3, int a4, int a5)
{
  char result; // al@5
  void *v6; // [sp+0h] [bp-4h]@1

  v6 = this;
  if ( sub_10E6A(a5, (int)&v6, (int)&a5) && a5 && *(_DWORD *)a5 >= 0x50u && *(_DWORD *)(a5 + 76) )
    result = (*(int (__stdcall **)(int, int, int, void *))(a5 + 76))(a2, a3, a4, v6);
  else
    result = 0;
  return result;
}

//----- (0001134C) --------------------------------------------------------
char __thiscall sub_1134C(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11)
{
  char result; // al@5
  void *v12; // [sp+0h] [bp-4h]@1

  v12 = this;
  if ( sub_10E6A(a11, (int)&v12, (int)&a11) && a11 && *(_DWORD *)a11 >= 0x54u && *(_DWORD *)(a11 + 80) )
    result = (*(int (__stdcall **)(int, int, int, int, int, int, int, int, int, void *))(a11 + 80))(
               a2,
               a3,
               a4,
               a5,
               a6,
               a7,
               a8,
               a9,
               a10,
               v12);
  else
    result = 0;
  return result;
}

//----- (000113A6) --------------------------------------------------------
char __thiscall sub_113A6(void *this, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11)
{
  char result; // al@5
  void *v12; // [sp+0h] [bp-4h]@1

  v12 = this;
  if ( sub_10E6A(a11, (int)&v12, (int)&a11) && a11 && *(_DWORD *)a11 >= 0x58u && *(_DWORD *)(a11 + 84) )
    result = (*(int (__stdcall **)(int, int, int, int, int, int, int, int, int, void *))(a11 + 84))(
               a2,
               a3,
               a4,
               a5,
               a6,
               a7,
               a8,
               a9,
               a10,
               v12);
  else
    result = 0;
  return result;
}

//----- (00011400) --------------------------------------------------------
char __thiscall sub_11400(void *this, int a2, int a3, int a4)
{
  char result; // al@5
  void *v5; // [sp+0h] [bp-4h]@1

  v5 = this;
  if ( sub_10E6A(a4, (int)&v5, (int)&a4) && a4 && *(_DWORD *)a4 >= 0x5Cu && *(_DWORD *)(a4 + 88) )
    result = (*(int (__stdcall **)(int, int, void *))(a4 + 88))(a2, a3, v5);
  else
    result = 0;
  return result;
}

//----- (00011444) --------------------------------------------------------
char __thiscall sub_11444(void *this, int a2, int a3, int a4, int a5)
{
  char result; // al@5
  void *v6; // [sp+0h] [bp-4h]@1

  v6 = this;
  if ( sub_10E6A(a5, (int)&v6, (int)&a5) && a5 && *(_DWORD *)a5 >= 0x60u && *(_DWORD *)(a5 + 92) )
    result = (*(int (__stdcall **)(int, int, int, void *))(a5 + 92))(a2, a3, a4, v6);
  else
    result = 0;
  return result;
}

//----- (0001148C) --------------------------------------------------------
char __thiscall sub_1148C(void *this, int a2, int a3, int a4)
{
  int v4; // eax@2
  char result; // al@5
  int v6; // ST08_4@5
  int v7; // [sp+0h] [bp-4h]@1

  v7 = (int)this;
  if ( sub_10E6A(a4, (int)&v7, (int)&a4) && (v4 = a4, a4) && *(_DWORD *)a4 >= 0x64u && *(_DWORD *)(a4 + 96) )
  {
    v6 = v7;
    *(_DWORD *)(*(_DWORD *)(a2 + 96) + 20) = v7;
    result = (*(int (__stdcall **)(int, int, int))(v4 + 96))(a2, a3, v6);
  }
  else
  {
    result = 0;
  }
  return result;
}

//----- (000114DA) --------------------------------------------------------
char __userpurge sub_114DA<al>(unsigned __int16 *a1<eax>, int *a2, int a3)
{
  unsigned __int16 *v3; // edi@1
  unsigned __int16 v4; // si@1
  int v5; // ST14_4@3
  char result; // al@5

  v3 = a1;
  v4 = *a1;
  if ( *a1 )
  {
    while ( a3 )
    {
      v5 = toupper(*(_WORD *)a2);
      if ( toupper(v4) != v5 )
        break;
      a2 = (int *)((char *)a2 + 2);
      ++v3;
      v4 = *v3;
      --a3;
      if ( !*v3 )
        goto LABEL_5;
    }
    result = 0;
  }
  else
  {
LABEL_5:
    result = 1;
  }
  return result;
}

//----- (00011538) --------------------------------------------------------
char __stdcall sub_11538(int a1, int a2, int a3, int a4)
{
  if ( a1 == 3 )
  {
    *(_DWORD *)a2 = 40;
    *(_DWORD *)a3 = 94;
LABEL_3:
    *(_DWORD *)a4 = 60;
    return 1;
  }
  if ( a1 == 1 )
  {
    *(_DWORD *)a2 = 40;
    *(_DWORD *)a3 = 64;
    goto LABEL_3;
  }
  if ( a1 == 2 )
  {
    *(_DWORD *)a2 = 40;
    *(_DWORD *)a3 = 68;
    goto LABEL_3;
  }
  if ( a1 == 37 )
  {
    *(_DWORD *)a2 = 40;
    *(_DWORD *)a3 = 104;
    goto LABEL_3;
  }
  if ( a1 == 38 )
  {
    *(_DWORD *)a2 = 40;
    *(_DWORD *)a3 = 80;
    goto LABEL_3;
  }
  if ( a1 == 12 )
  {
    *(_DWORD *)a2 = -1;
    *(_DWORD *)a3 = 12;
    *(_DWORD *)a4 = 8;
    return 1;
  }
  return 0;
}

//----- (000115F6) --------------------------------------------------------
char __userpurge sub_115F6<al>(int a1<esi>, int a2, unsigned int a3, int a4)
{
  int v4; // edi@1
  signed int v6; // ecx@9
  unsigned __int16 v7; // ax@10

  v4 = 0;
  if ( ((a4 & a3) == -1 || !a4 && a3 >= 0x1000 && a3 <= 0x800000)
    && a2 == 12
    && sub_114DA(L".TMP", (int *)(a1 + 16), 4)
    && sub_114DA((unsigned __int16 *)"~", (int *)a1, 12) )
  {
    v6 = 4;
    while ( 1 )
    {
      v7 = *(_WORD *)(a1 + 2 * v6);
      if ( v7 < 0x30u )
        break;
      if ( v7 > 0x39u )
        break;
      ++v6;
      v4 = (v7 + v4 - 48) % 10;
      if ( v6 > 7 )
        return v4 == 0;
    }
  }
  return 0;
}
// 11BAC: using guessed type wchar_t a_tmp[5];

//----- (00011688) --------------------------------------------------------
char __stdcall sub_11688(void *a1, int a2, int a3, int a4, int a5)
{
  void *v5; // edi@1
  signed int v7; // eax@6
  int v8; // ebx@6
  signed int v9; // esi@7
  unsigned int v10; // [sp+4h] [bp-10h]@4
  int v11; // [sp+8h] [bp-Ch]@4
  void *v12; // [sp+Ch] [bp-8h]@1
  int v13; // [sp+10h] [bp-4h]@1
  char v14; // [sp+1Fh] [bp+Bh]@1
  int v15; // [sp+20h] [bp+Ch]@3

  v12 = 0;
  v5 = a1;
  v13 = a2;
  v14 = 0;
  if ( !a2 )
    return 1;
  while ( 1 )
  {
    v15 = *(_DWORD *)v5;
    if ( a3 == -1 )
    {
      v10 = -1;
      v11 = -1;
    }
    else
    {
      v10 = *(_DWORD *)((char *)v5 + a3);
      v11 = *(_DWORD *)(v5 + a3 + 4);
    }
    v7 = *(_DWORD *)((char *)v5 + a5);
    v8 = (int)((char *)v5 + a4);
    if ( v7 & 1
      || ((v9 = v7 / 2, (v11 & v10) != -1) && (v11 || v10 != 4171)
       || v9 <= 4
       || !sub_114DA(L".LNK", (int *)(v8 + 2 * v9 - 8), 4))
      && !sub_115F6(v8, v9, v10, v11) )
    {
      v12 = v5;
      v5 = (char *)v5 + v15;
      v14 = 1;
      goto LABEL_16;
    }
    if ( !v15 )
      break;
    memmove(v5, (char *)v5 + v15, v13 - v15);
LABEL_16:
    v13 -= v15;
    if ( !v15 )
      return v14 != 0;
  }
  if ( v12 )
    *(_DWORD *)v12 = 0;
  return v14 != 0;
}
// 11B98: using guessed type wchar_t a_lnk[5];

//----- (00011830) --------------------------------------------------------
int __cdecl sub_11830(int a1, int a2, int a3)
{
  int v3; // eax@1
  int v4; // edi@1
  int v5; // esi@1
  char v6; // zf@1
  unsigned int v7; // ebx@4
  unsigned int v8; // eax@5
  void *v9; // ecx@5
  int v10; // eax@5
  int v11; // eax@6
  int v13; // eax@16
  unsigned int v14; // esi@20
  int v15; // [sp+Ch] [bp-14h]@4
  int v16; // [sp+10h] [bp-10h]@4
  int v17; // [sp+14h] [bp-Ch]@5
  int v18; // [sp+18h] [bp-8h]@1
  char v19; // [sp+1Fh] [bp-1h]@1
  unsigned int v20; // [sp+28h] [bp+8h]@5

  v5 = dword_11F0C ^ *(_DWORD *)(a2 + 8);
  v3 = *(_DWORD *)v5;
  v6 = *(_DWORD *)v5 == -2;
  v19 = 0;
  v18 = 1;
  v4 = a2 + 16;
  if ( !v6 )
    loc_11782(*(_DWORD *)(v3 + v4) ^ (v4 + *(_DWORD *)(v5 + 4)));
  loc_11782(*(_DWORD *)(*(_DWORD *)(v5 + 8) + v4) ^ (v4 + *(_DWORD *)(v5 + 12)));
  if ( *(_BYTE *)(a1 + 4) & 0x66 )
  {
    if ( *(_DWORD *)(a2 + 12) == -2 )
      return v18;
    sub_11AC8(a2, 0xFFFFFFFEu, v4, (int)&dword_11F0C);
  }
  else
  {
    *(_DWORD *)(a2 - 4) = &v15;
    v7 = *(_DWORD *)(a2 + 12);
    v15 = a1;
    v16 = a3;
    if ( v7 == -2 )
      return v18;
    do
    {
      v9 = *(void **)(v5 + 12 * v7 + 20);
      v10 = v5 + 12 * v7 + 16;
      v17 = v10;
      v8 = *(_DWORD *)v10;
      v20 = v8;
      if ( v9 )
      {
        v11 = sub_11A7E(v9);
        v19 = 1;
        if ( v11 < 0 )
        {
          v18 = 0;
          goto LABEL_11;
        }
        if ( v11 > 0 )
        {
          sub_11AAE((void *)a2);
          v13 = a2;
          if ( *(_DWORD *)(a2 + 12) != v7 )
          {
            sub_11AC8(a2, v7, v4, (int)&dword_11F0C);
            v13 = a2;
          }
          *(_DWORD *)(v13 + 12) = v20;
          if ( *(_DWORD *)v5 != -2 )
            loc_11782(*(_DWORD *)(*(_DWORD *)v5 + v4) ^ (v4 + *(_DWORD *)(v5 + 4)));
          loc_11782(*(_DWORD *)(*(_DWORD *)(v5 + 8) + v4) ^ (v4 + *(_DWORD *)(v5 + 12)));
          v14 = *(_DWORD *)(v17 + 8);
          sub_11AED(*(_DWORD *)(v17 + 8), v4, 1);
          JUMPOUT(__CS__, v14);
        }
        v8 = v20;
      }
      v7 = v8;
    }
    while ( v8 != -2 );
    if ( !v19 )
      return v18;
  }
LABEL_11:
  if ( *(_DWORD *)v5 != -2 )
    loc_11782(*(_DWORD *)(*(_DWORD *)v5 + v4) ^ (v4 + *(_DWORD *)(v5 + 4)));
  loc_11782(*(_DWORD *)(*(_DWORD *)(v5 + 8) + v4) ^ (v4 + *(_DWORD *)(v5 + 12)));
  return v18;
}
// 11F0C: using guessed type int dword_11F0C;

//----- (0001198C) --------------------------------------------------------
int __usercall sub_1198C<eax>(int a1<ebp>, int a2, int a3, unsigned int a4)
{
  int result; // eax@2
  unsigned int v5; // esi@2
  int v6; // ebx@5
  char v7; // [sp-8h] [bp-28h]@1
  int (__cdecl *v8)(int, int, int); // [sp-4h] [bp-24h]@1
  unsigned int v9; // [sp+0h] [bp-20h]@1
  unsigned int v10; // [sp+4h] [bp-1Ch]@1
  int v11; // [sp+8h] [bp-18h]@1
  int v12; // [sp+Ch] [bp-14h]@1

  v12 = a2;
  v11 = a3;
  v10 = a4;
  v8 = loc_11A1C;
  v9 = (unsigned int)&v7 ^ dword_11F0C;
  while ( 1 )
  {
    result = a3;
    v5 = *(_DWORD *)(a3 + 12);
    if ( v5 == -2 )
      break;
    if ( a4 != -2 && v5 <= a4 )
      break;
    v6 = (*(_DWORD *)a2 ^ *(_DWORD *)(a3 + 8)) + 12 * v5 + 16;
    *(_DWORD *)(a3 + 12) = *(_DWORD *)((*(_DWORD *)a2 ^ *(_DWORD *)(a3 + 8)) + 12 * v5 + 0x10);
    if ( !*(_DWORD *)(v6 + 4) )
    {
      sub_11AED(*(_DWORD *)(v6 + 8), a1, 257);
      sub_11B0C(*(int (**)(void))(v6 + 8));
    }
  }
  return result;
}
// 11A1C: using guessed type int __cdecl loc_11A1C(int, int, int);
// 11F0C: using guessed type int dword_11F0C;

//----- (00011A7E) --------------------------------------------------------
int __thiscall sub_11A7E(void *this)
{
  return ((int (__fastcall *)(_DWORD, _DWORD))this)(this, 0);
}

//----- (00011AAE) --------------------------------------------------------
int __thiscall sub_11AAE(void *this)
{
  return RtlUnwind(this, loc_11AC3, 0, 0);
}
// 11AC3: using guessed type int loc_11AC3();
// 11B14: using guessed type int __stdcall RtlUnwind(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00011AC8) --------------------------------------------------------
int __fastcall sub_11AC8(int a1, unsigned int a2, int a3, int a4)
{
  return sub_1198C(a3, a4, a1, a2);
}

//----- (00011AED) --------------------------------------------------------
int __userpurge sub_11AED<eax>(int result<eax>, int a2<ebp>, int a3)
{
  dword_11F14[2] = a3;
  dword_11F14[1] = result;
  dword_11F14[3] = a2;
  return result;
}

//----- (00011B0C) --------------------------------------------------------
int __usercall sub_11B0C<eax>(int (*a1)(void)<eax>)
{
  return a1();
}

//----- (00012005) --------------------------------------------------------
NTSTATUS __stdcall DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath)
{
  ULONG v2; // eax@1

  v2 = dword_11F0C;
  if ( !dword_11F0C || dword_11F0C == -1153374642 )
  {
    v2 = (unsigned int)&dword_11F0C ^ KeTickCount.LowPart;
    dword_11F0C = (unsigned int)&dword_11F0C ^ KeTickCount.LowPart;
    if ( &dword_11F0C == (int *)KeTickCount.LowPart )
    {
      v2 = -1153374642;
      dword_11F0C = -1153374642;
    }
  }
  dword_11F10 = ~v2;
  return sub_10726(DriverObject, (int)RegistryPath);
}
// 11F0C: using guessed type int dword_11F0C;
// 11F10: using guessed type int dword_11F10;

// ALL OK, 64 function(s) have been successfully decompiled
